package com.sapienter.jbilling.test.framework;

/**
 * @author Vojislav Stanojevikj
 * @since 15-Jun-2016.
 */
public enum TestEntityType {

    CUSTOMER, AGENT, PRODUCT, ORDER, INVOICE, PAYMENT,ACCOUNT_TYPE, PRODUCT_CATEGORY, PLAN,
    ASSET, ORDER_CHANGE, ORDER_LINE, PAYMENT_METHOD_TYPE, MEDIATION_CONFIGURATION,
    PAYMENT_METHOD_TEMPLATE, ACCOUNT_INFORMATION_TYPE, ENUMERATION, META_FIELD,
    PLUGGABLE_TASK, COMPANY, ROUTE, USAGE_POOL, ORDER_CHANGE_STATUS , DISCOUNT, ORDER_PERIOD,
    NOTIFICATION_TYPE, ORDER_CHANGE_TYPE, INVOICE_STATUS, EDI_TYPE, ENROLLMENT,
    USAGE_RATING_SCHEME

}
