/*
 * JBILLING CONFIDENTIAL
 * _____________________
 *
 * [2003] - [2012] Enterprise jBilling Software Ltd.
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Enterprise jBilling Software.
 * The intellectual and technical concepts contained
 * herein are proprietary to Enterprise jBilling Software
 * and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden.
 */

/*
 * Generated by XDoclet - Do not edit!
 */
package com.sapienter.jbilling.server.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.sapienter.jbilling.common.Util;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

import javax.xml.bind.annotation.XmlType;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Value object for InvoiceLineEntity.
 */
@XmlType(name = "invoice-line")
@ApiModel(value = "Invoice line data", description = "InvoiceLineDTO model")
public class InvoiceLineDTO implements Serializable {

    private Integer id;
    private String description;
    private String amount;
    private String price;
    private String quantity;
    private Integer deleted;
    private Integer itemId;
    private Integer sourceUserId;
    private Integer isPercentage;
    private String callIdentifier;
    private Integer usagePlanId;
    private Long callCounter = 0l;

    private String taxRate;
    private String taxAmount;
    private String grossAmount;
    private Integer typeId;

    public InvoiceLineDTO() {
    }

    public InvoiceLineDTO(Integer id, String description, BigDecimal amount, BigDecimal price, BigDecimal quantity,
                          Integer deleted, Integer itemId, Integer sourceUserId, Integer percentage,
                          String callIdentifier, Integer usagePlanId, Long callCounter) {
        this.id = id;
        this.description = description;
        setAmount(amount);
        setPrice(price);
        setQuantity(quantity);
        this.deleted = deleted;
        this.itemId = itemId;
        this.sourceUserId = sourceUserId;
        isPercentage = percentage;
        this.callIdentifier = callIdentifier;
        this.usagePlanId = usagePlanId;
        this.callCounter = callCounter;
    }

    public InvoiceLineDTO(Integer id, String description, BigDecimal amount, BigDecimal price, BigDecimal quantity,
            Integer deleted, Integer itemId, Integer sourceUserId, Integer percentage,
            String callIdentifier, Integer usagePlanId, Long callCounter, String taxRate, String taxAmount,
            String grossAmount) {
        this.id = id;
        this.description = description;
        setAmount(amount);
        setPrice(price);
        setQuantity(quantity);
        this.deleted = deleted;
        this.itemId = itemId;
        this.sourceUserId = sourceUserId;
        isPercentage = percentage;
        this.callIdentifier = callIdentifier;
        this.usagePlanId = usagePlanId;
        this.callCounter = callCounter;
        this.taxRate = taxRate;
        this.taxAmount = taxAmount;
        this.grossAmount = grossAmount;
    }

    public InvoiceLineDTO(InvoiceLineDTO otherValue) {
        this.id = otherValue.id;
        this.description = otherValue.description;
        this.amount = otherValue.amount;
        this.price = otherValue.price;
        this.quantity = otherValue.quantity;
        this.deleted = otherValue.deleted;
        this.itemId = otherValue.itemId;
        this.sourceUserId = otherValue.sourceUserId;
        this.isPercentage = otherValue.isPercentage;
        this.callIdentifier = otherValue.callIdentifier;
        this.usagePlanId =otherValue.usagePlanId;
        this.callCounter = otherValue.callCounter;
        this.taxRate = otherValue.getTaxRate();
        this.taxAmount = otherValue.getTaxAmount();
        this.grossAmount = otherValue.getGrossAmount();
    }

    @ApiModelProperty(value = "Unique identifier of the invoice line")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ApiModelProperty(value = "Description used in the invoice delivered to the customer")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @JsonIgnore
    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = (amount != null ? amount.toString() : null);
    }

    @ApiModelProperty(value = "The total amount of this invoice line", dataType = "BigDecimal")
    @JsonProperty(value = "amount")
    public BigDecimal getAmountAsDecimal() {
        return amount == null ? null : new BigDecimal(amount);
    }

    public void setAmountAsDecimal(BigDecimal amount) {
        setAmount(amount);
    }

    @JsonIgnore
    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public void setPrice(BigDecimal price) {
        this.price = (price != null ? price.toString() : null);
    }

    @ApiModelProperty(value = "The price for a singel unit of the item in the invoice line", dataType = "BigDecimal")
    @JsonProperty(value = "price")
    public BigDecimal getPriceAsDecimal() {
        return price == null ? null : new BigDecimal(price);
    }

    public void setPriceAsDecimal(BigDecimal price) {
        setPrice(price);
    }

    @JsonIgnore
    public String getQuantity() {
        return quantity;
    }

    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    public void setQuantity(BigDecimal quantity) {
        this.quantity = (quantity != null ? quantity.toString() : null);
    }

    @ApiModelProperty(value = "The number of units in the invoice line", dataType = "BigDecimal")
    @JsonProperty(value = "quantity")
    public BigDecimal getQuantityAsDecimal() {
        return quantity == null ? null : new BigDecimal(quantity);
    }

    public void setQuantityAsDecimal(BigDecimal quantity) {
        setQuantity(quantity);
    }

    @ApiModelProperty(value = "Flag that indicates if this record is logically deleted in the database." +
            " 0 - not deleted; 1 - deleted")
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    @ApiModelProperty(value = "Unique identifier of the item used in the invoice line")
    public Integer getItemId() {
        return itemId;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    @ApiModelProperty(value = "Used when many sub-accounts are invoiced together." +
            " This field would have the id of the user that originally purchased an item")
    public Integer getSourceUserId() {
        return sourceUserId;
    }

    public void setSourceUserId(Integer sourceUserId) {
        this.sourceUserId = sourceUserId;
    }

    @ApiModelProperty(value = "Indicates whether the item referenced by this invoice line is a percentage item or not")
    public Integer getPercentage() {
        return isPercentage;
    }

    public void setPercentage(Integer percentage) {
        isPercentage = percentage;
    }

    @Override
    public String toString() {
        return "InvoiceLineDTO{" +
                "id=" + id +
                ", description='" + description + '\'' +
                ", amount=" + amount +
                ", price=" + price +
                ", quantity=" + quantity +
                ", deleted=" + deleted +
                ", itemId=" + itemId +
                ", sourceUserId=" + sourceUserId +
                ", isPercentage=" + isPercentage +
                ", usagePlanId=" + usagePlanId +
                ", callCounter=" + callCounter +
                ", taxRate=" + taxRate +
                ", taxAmount=" + taxAmount +
                ", grossAmount=" + grossAmount +
                '}';
    }

	public String getCallIdentifier() {
		return callIdentifier;
	}

	public void setCallIdentifier(String callIdentifier) {
		this.callIdentifier = callIdentifier;
	}

	public Integer getUsagePlanId() {
		return usagePlanId;
	}

	public void setUsagePlanId(Integer usagePlanId) {
		this.usagePlanId = usagePlanId;
	}

	public Long getCallCounter() {
		return callCounter;
	}

	public void setCallCounter(Long callCounter) {
		this.callCounter = callCounter;
	}

    @JsonIgnore
    public String getTaxRate() {
        return taxRate;
    }

    public void setTaxRate(String taxRate) {
        this.taxRate = taxRate;
    }

    @JsonIgnore
    public String getTaxAmount() {
        return taxAmount;
    }

    public void setTaxAmount(String taxAmount) {
        this.taxAmount = taxAmount;
    }

    @JsonIgnore
    public String getGrossAmount() {
        return grossAmount;
    }
    
    @ApiModelProperty(value = "The Tax Rate of this invoice line", dataType = "BigDecimal")
    @JsonProperty(value = "taxRate")
    public BigDecimal getTaxRateAsDecimal() {
        return Util.string2decimal(taxRate);
    }
    
    @ApiModelProperty(value = "The Tax Amount of this invoice line", dataType = "BigDecimal")
    @JsonProperty(value = "taxAmount")
    public BigDecimal getTaxAmountAsDecimal() {
        return Util.string2decimal(taxAmount);
    }
    
    @ApiModelProperty(value = "The grossAmount of this invoice line", dataType = "BigDecimal")
    @JsonProperty(value = "grossAmount")
    public BigDecimal getGrossAmountAsDecimal() {
        return Util.string2decimal(grossAmount);
    }

    public void setGrossAmount(String grossAmount) {
        this.grossAmount = grossAmount;
    }

    public Integer getTypeId() {
        return typeId;
    }

    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

}
