FROM ubuntu:22.04

MAINTAINER ashwinkumarp "ashwin.patra@sarathisoftech.com"

ENV LANG="en_US.UTF-8"
ENV LANGUAGE="en_US:en"
ENV LC_ALL="en_US.UTF-8"

# Defining default Java and Maven version
ARG JAVA_VERSION="8.0.282.hs-adpt"
ARG MAVEN_VERSION="3.6.3"
ARG GRAILS_VERSION="2.4.3"
ARG ANT_VERSION="1.10.3"

# Defining default non-root user UID, GID, and name
ARG USER_UID="134"
ARG USER_GID="142"
ARG USER_NAME="jenkins"

# Creating default non-user
RUN groupadd -g $USER_GID $USER_NAME && \
	useradd -m -g $USER_GID -u $USER_UID $USER_NAME

# Installing basic packages
RUN apt-get update && \
	apt-get install -y wget zip unzip curl git gnupg locales nano net-tools lsb-release ca-certificates apt-transport-https software-properties-common && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /tmp/*


# Installing font packages
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get update -y
RUN apt-get install -y apt-utils    --no-install-recommends
RUN apt-get install -y libfreetype6 --no-install-recommends
RUN apt-get install -y fontconfig   --no-install-recommends
RUN apt-get install -y fonts-dejavu --no-install-recommends

## Docker Installation
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt update && \
    apt install -y docker-ce

#ADD /var/run/docker.sock ./var/run/

# Switching to non-root user to install SDKMAN!
USER $USER_UID:$USER_GID

# Downloading SDKMAN!
RUN curl -s "https://get.sdkman.io" | bash

# Installing Java and Maven, removing some unnecessary SDKMAN files
RUN bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && \
    yes | sdk install java $JAVA_VERSION && \
    yes | sdk install maven $MAVEN_VERSION && \
    yes | sdk install grails $GRAILS_VERSION && \
    yes | sdk install ant $ANT_VERSION && \
    rm -rf $HOME/.sdkman/archives/* && \
    rm -rf $HOME/.sdkman/tmp/*"

# ENTRYPOINT bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && $0 $@"

ENV MAVEN_HOME="/home/jenkins/.sdkman/candidates/maven/current"
ENV JAVA_HOME="/home/jenkins/.sdkman/candidates/java/current"
ENV GRAILS_HOME="/home/jenkins/.sdkman/candidates/grails/current"
ENV ANT_HOME="/home/jenkins/.sdkman/candidates/ant/current"
ENV DOCKER_COMPOSE_HOME="/usr/local/bin/"
ENV PATH="$MAVEN_HOME/bin:$JAVA_HOME/bin:$GRAILS_HOME/bin:$ANT_HOME/bin:$DOCKER_COMPOSE_HOME:$PATH"
ENV POSTGRES_USER="jbilling"
ENV POSTGRES_DB="jbilling_test"
ENV POSTGRES_PASSWORD=""
ENV POSTGRES_HOST_AUTH_METHOD="trust"
ENV JBILLING_DB_HOST_MEDIATION4="localhost"
ENV JBILLING_DB_PORT_MEDIATION4="5432"
ENV JBILLING_DB_NAME_MEDIATION4="jbilling_test"
ENV JBILLING_DB_USER_MEDIATION4="jbilling"
ENV JBILLING_DB_PASSWORD_MEDIATION4=""
