version: '3.7'
services:
#  tomcat:
#    image: tomcat:8-alpine
#    container_name: earnbill_tomcat
#    ports:
#      - "8080:8080"
#    restart: always
#    command: [ "catalina.sh", "run" ]
#    environment:
#      - POSTGRES_USER=jbilling
#      - POSTGRES_PASSWORD=
#      - POSTGRES_DB=jbilling_test
#      - JBILLING_DB_HOST_MEDIATION4=localhost
#      - JBILLING_DB_PORT_MEDIATION4=5432
#      - JBILLING_DB_NAME_MEDIATION4=jbilling_test
#      - JBILLING_DB_USER_MEDIATION4=jbilling
#      - JBILLING_DB_PASSWORD_MEDIATION4=
#      - JBILLING_SERVER_URL=http://localhost:8080/jbilling
#      - JBILLING_HOST=localhost
#      - JBILLING_DB_HOST=localhost
#      - SPRING_PROFILES_ACTIVE=billing.master,billing.slave,mediation.slave
#    expose:
#      - 8080
#    depends_on:
#      - postgres
#    volumes:
#      #      - ./webapps:/usr/local/tomcat/webapps
#      - ./target/sample.war:/usr/local/tomcat/webapps/sample.war
##      - $HOME/docker_logs:/usr/local/tomcat/webapps/logs
#    networks:
#      - default
#    user: root
#    privileged: true

  postgres:
    image: postgres:13.2-alpine
    container_name: earnbill_postgres
    environment:
      - POSTGRES_USER=jbilling
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=jbilling_test
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - default
    command: -p ${POSTGRES_PORT}
    user: root
    privileged: true
    restart: always

networks:
  default:
    name: earnbill_integration_test
    driver: bridge
    external: true
