package com.sapienter.jbilling.server.report.db;

public abstract class ReportSQLQueries {

    private ReportSQLQueries() {
    }

    public static final String ACTIVE_SERVICES_REPORT = ""
            + "SELECT bu.id, "
            + "                        bu.user_name, "
            + "                        CONCAT( "
            + "                               (SELECT DISTINCT mfv.string_value "
            + "                                  FROM customer_account_info_type_timeline caitt "
            + "                                 INNER JOIN meta_field_value mfv ON caitt.meta_field_value_id = mfv.id "
            + "                                 INNER JOIN meta_field_name mfn ON mfv.meta_field_name_id=mfn.id AND mfn.name ='Title' "
            + "                                 WHERE caitt.customer_id = cu.id), "
            + "                               (SELECT DISTINCT CASE WHEN mfv.string_value is not null THEN ' '||  mfv.string_value  END "
            + "                                  FROM customer_account_info_type_timeline caitt "
            + "                                 INNER JOIN meta_field_value mfv ON caitt.meta_field_value_id = mfv.id "
            + "                                 INNER JOIN meta_field_name mfn ON mfv.meta_field_name_id=mfn.id AND mfn.name ='First Name' "
            + "                                 WHERE caitt.customer_id = cu.id), "
            + "                               (SELECT DISTINCT CASE WHEN mfv.string_value is not null THEN ' '||  mfv.string_value  END "
            + "                                  FROM customer_account_info_type_timeline caitt "
            + "                                 INNER JOIN meta_field_value mfv ON caitt.meta_field_value_id = mfv.id "
            + "                                 INNER JOIN meta_field_name mfn ON mfv.meta_field_name_id=mfn.id AND mfn.name ='Last Name' "
            + "                                 WHERE caitt.customer_id = cu.id)) AS \"Full Name\", "
            + "                               pu.id AS \"Order Id\", "
            + "                               (SELECT mfv.string_value FROM order_meta_field_map omfm "
            + "                                 INNER JOIN meta_field_value mfv ON mfv.id = omfm.meta_field_value_id "
            + "                                 INNER JOIN meta_field_name mfn ON mfv.meta_field_name_id = mfn.id AND mfn.name = 'amaysim Order ID' "
            + "                                                                                                   AND mfn.is_primary = 't' "
            + "                                 WHERE omfm.order_id = pu.id) AS \"amaysim Order ID\", "
            + "                               itm.id \"Prod Id\", "
            + "                               ol.description, "
            + "                               ol.amount, "
            + "     				          (CASE WHEN " 
            + "		                          (SELECT id FROM plan WHERE item_id=ol.item_id) is not null THEN "
            + "		                          ((ol.amount * (CAST((SELECT tax_rate FROM route_70_tax_scheme "
            + "                               WHERE description =((SELECT mfv.string_value  FROM plan_meta_field_map pmfm  " 
            + "                               INNER JOIN meta_field_value mfv on pmfm.meta_field_value_id=mfv.id "
            + "                               INNER JOIN meta_field_name mfn on mfv.meta_field_name_id=mfn.id and "
            + "                               mfn.name = 'Tax Scheme'   AND pmfm.plan_id = (select id from plan where item_id=ol.item_id) ))) "
            + "                               AS DOUBLE PRECISION ) /100)))"
            + "                               ELSE "
            + "                               ((ol.amount * (CAST((SELECT tax_rate FROM route_70_tax_scheme WHERE description = "
            + "                               ((SELECT mfv.string_value    FROM item itm "
            + "                               INNER JOIN item_meta_field_map imfm ON imfm.item_id = itm.id "
            + "                               INNER JOIN meta_field_value mfv ON mfv.id = imfm.meta_field_value_id  "
            + "                               INNER JOIN meta_field_name mfn ON mfn.name = 'Tax Scheme' AND mfv.meta_field_name_id = mfn.id "
            + "                               AND itm.id = ol.item_id ))) AS DOUBLE PRECISION ) /100))) END) "
            + "		                          AS \"GST\", "
            + "                               (ol.amount +  "
            + "                               (CASE WHEN " 
            + "		                          (SELECT id FROM plan WHERE item_id=ol.item_id) is not null THEN "
            + "		                          ((ol.amount * (CAST((SELECT tax_rate FROM route_70_tax_scheme "
            + "                               WHERE description =((SELECT mfv.string_value  FROM plan_meta_field_map pmfm  " 
            + "                               INNER JOIN meta_field_value mfv on pmfm.meta_field_value_id=mfv.id "
            + "                               INNER JOIN meta_field_name mfn on mfv.meta_field_name_id=mfn.id and "
            + "                               mfn.name = 'Tax Scheme'   AND pmfm.plan_id = (select id from plan where item_id=ol.item_id) ))) "
            + "                               AS DOUBLE PRECISION ) /100)))"
            + "                               ELSE "
            + "                               ((ol.amount * (CAST((SELECT tax_rate FROM route_70_tax_scheme WHERE description = "
            + "                               ((SELECT mfv.string_value    FROM item itm "
            + "                               INNER JOIN item_meta_field_map imfm ON imfm.item_id = itm.id "
            + "                               INNER JOIN meta_field_value mfv ON mfv.id = imfm.meta_field_value_id  "
            + "                               INNER JOIN meta_field_name mfn ON mfn.name = 'Tax Scheme' AND mfv.meta_field_name_id = mfn.id "
            + "                               AND itm.id = ol.item_id ))) AS DOUBLE PRECISION ) /100))) END) ) AS  \"Price Inc GST\", "
            + "                               pu.create_datetime, "
            + "                               pu.active_since, "
            + "                               pu.active_until, "
            + "                               pu.next_billable_day, "
            + "                               (SELECT content FROM international_description "
            + "                                 WHERE foreign_id = pu.period_id "
            + "                                       AND table_id = (SELECT id FROM jbilling_table WHERE name='order_period') "
            + "                                       AND language_id = 1) AS \"Order Period\", "
            + "                               CASE WHEN (pu.next_billable_day is not null) AND (pu.active_since > now() :: date) "
            + "                                                                            AND (pu.period_id != 1) THEN 'Pending' "
            + "                                    WHEN (pu.period_id = 1) AND (pu.active_since > now() :: date) THEN 'Pending' "
            + "                                    ELSE (SELECT content FROM international_description "
            + "                                           WHERE foreign_id = pu.status_id "
            + "                                                 AND table_id = (SELECT id FROM jbilling_table "
            + "                                                                  WHERE name='order_status') "
            + "                                                 AND language_id = 1) "
            + "                                     END AS \"Order Status\", "
            + "                              (SELECT content FROM international_description "
            + "                                WHERE foreign_id = pu.billing_type_id "
            + "                                      AND table_id = (SELECT id FROM jbilling_table "
            + "                                                       WHERE name='order_billing_type') "
            + "                                      AND language_id = 1) AS \"Type\", "
            + "                             (CASE WHEN (pu.parent_order_id != null) "
            + "                                   THEN 'Child' "
            + "                                   ELSE 'Parent' "
            + "                                    END) AS \"Parent/child\", "
            + "                        (SELECT due_date "
            + "                           FROM invoice "
            + "                          WHERE user_id = bu.id "
            + "                       ORDER BY due_date DESC limit 1 ) AS due_date, "
            + "                        (SELECT string_value "
            + "                           FROM meta_field_value "
            + "                     INNER JOIN customer_meta_field_map ON meta_field_value.id = customer_meta_field_map.meta_field_value_id "
            + "                                                       AND customer_meta_field_map.customer_id = cu.id "
            + "                     INNER JOIN meta_field_name ON meta_field_value.meta_field_name_id = meta_field_name.id "
            + "                                               AND meta_field_name.name = 'crmAccountNumber' "
            + "                                               AND meta_field_name.entity_type = 'CUSTOMER' "
            + "                                               AND meta_field_name.entity_id = bu.entity_id) AS crmAccountNumber, "
            + "                     (CASE WHEN (ol.call_identifier IS NOT NULL) "
            + "                           THEN ol.call_identifier "
            + "                           ELSE "
            + "                     (SELECT string_agg(distinct ast.identifier,',') "
            + "                        FROM asset ast "
            + "                       INNER JOIN order_line line ON line.id = ast.order_line_id "
            + "                       INNER JOIN item it ON it.id = line.item_id "
            + "                       INNER JOIN purchase_order po ON bu.id = po.user_id "
            + "                       INNER JOIN order_status os ON os.id = po.status_id "
            + "                       WHERE line.order_id = pu.id AND po.deleted = 0 AND os.order_status_flag = 0 AND line.deleted = 0 AND os.entity_id = bu.entity_id "
            + "                     ) END) AS \"Asset Identifiers\", "
            + "                     (SELECT COALESCE(CASE WHEN (ol.call_identifier IS NOT NULL) "
            + "                                           THEN "
            + "                     (SELECT string_agg(string_value ,',') "
            + "                        FROM meta_field_value mfv "
            + "                       INNER JOIN asset_meta_field_map map ON map.meta_field_value_id = mfv.id "
            + "                       INNER JOIN meta_field_name mfn ON mfn.id = mfv.meta_field_name_id "
            + "                       WHERE map.asset_id in (select id from asset where identifier = ol.call_identifier) AND mfn.name = 'ServiceId' AND mfn.entity_type = 'ASSET' "
            + "                         AND mfn.entity_id = bu.entity_id) "
            + "                                           ELSE "
            + "                     (SELECT string_agg(string_value ,',') "
            + "                        FROM meta_field_value mfv "
            + "                       INNER JOIN asset_meta_field_map map ON map.meta_field_value_id = mfv.id "
            + "                       INNER JOIN meta_field_name mfn ON mfn.id = mfv.meta_field_name_id "
            + "                       WHERE map.asset_id in (select id from asset where order_line_id in (select id from order_line where order_id = pu.id)) AND mfn.name = 'ServiceId' AND mfn.entity_type = 'ASSET' "
            + "                         AND mfn.entity_id = bu.entity_id) END, "
            + "                     (SELECT string_value "
            + "                        FROM meta_field_value mfv"
            + "                       INNER JOIN order_line_meta_field_map map ON map.meta_field_value_id = mfv.id "
            + "                       INNER JOIN meta_field_name mfn ON mfn.id = mfv.meta_field_name_id "
            + "                       WHERE map.order_line_id = ol.id AND mfn.name = 'ServiceId' AND mfn.entity_type = 'ORDER_LINE' "
            + "                         AND mfn.entity_id = bu.entity_id))) AS \"Service Id\" ,"
            + "                     (SELECT mfv.string_value FROM order_meta_field_map omfm   INNER JOIN meta_field_value mfv ON mfv.id = omfm.meta_field_value_id  "
            + "                      INNER JOIN meta_field_name mfn ON mfv.meta_field_name_id = mfn.id AND mfn.name = 'crmOrderNumber' AND mfn.is_primary = 't'   "
            + "                      AND mfn.entity_type = 'ORDER' WHERE omfm.order_id = pu.id AND mfn.entity_id = bu.entity_id ) AS crmOrderNumber  ,"
            + "                 (SELECT id from plan where item_id=itm.id ) AS \"Plan Id\"  ,"
            + "                 (CASE WHEN (pu.prorate_flag = 't')  THEN 'YES'  ELSE 'NO'  END) as \"IsProrated \"  "
            + "                 FROM base_user bu "
            + "                 INNER JOIN customer cu ON cu.user_id = bu.id "
            + "                 INNER JOIN purchase_order pu ON bu.id = pu.user_id AND pu.deleted =0 "
            + "                                                                     AND pu.status_id in (SELECT id FROM order_status "
            + "                                                                                           WHERE order_status_flag =0 AND entity_id = bu.entity_id) "
            + "                 INNER JOIN order_line ol ON ol.order_id = pu.id AND ol.deleted = 0 "
            + "                 INNER JOIN item itm ON itm.id = ol.item_id AND itm.asset_management_enabled = 0"
            + "                 WHERE bu.entity_id = %d"
            + "                 ORDER BY bu.id, pu.id ";

    public static final String DETAILED_BILLING_REPORT = 
            "  SELECT invoice_date AS \"Invoice Date\", "
                    + "  invoice_id AS \"Invoice Number\", "
                    + "  user_id AS \"Customer Number\", "
                    + "  user_name AS \"Customer Name\", "
                    + "  origin AS \"Origin\", "
                    + "  service_email AS \"Service Email\", "
                    + "  service_number AS \"Service Number\", "
                    + "  product_code AS \"Plan Or Product Code\", "
                    + "  plan_or_product_name AS \"Plan Or Product Name\", "
                    + "  plan_type AS \"Plan Type\", "
                    + "  from_date AS \"From Date\", "
                    + "  to_date AS \"To Date\", "
                    + "  product_end_date AS \"Product End Date\", "
                    + "  tariff_code AS \"Tariff Code\", "
                    + "  tariff_description AS \"Tariff Description\", "
                    + "  rollup_code AS\" Rollup Code\", "
                    + "  rollup_description \"Rollup Description\", "
                    + "  super_rollup_code AS \"Super Rollup Code\", "
                    + "  super_rollup_description AS \"Super Rollup Description\", "
                    + "  super_super_rollup_code AS \"Super Super Rollup Code\", "
                    + "  super_super_rollup_description AS \"Super Super Rollup Description\", "
                    + "  tax_code AS \"Tax Code\", "
                    + "  service_type AS \"Service Type\", "
                    + "  service_description AS \"Service Description\", "
                    + "  revenue_gl_code AS \"Revenue GL Code\", "
                    + "  COALESCE(sales_ex_gst,0) AS \"Sales Ex GST\", "
                    + "  COALESCE(gst,0) AS \"GST\", "
                    + "  COALESCE(sales_ex_gst,0) + COALESCE(gst,0) AS \"Sales Including Gst\", "
                    + "  costs_gl_code AS \"Costs GL Code\", "
                    + "  COALESCE(cost_of_service,0) AS \"Cost Of Service\" "
                    + "  FROM detailed_billing_log "
                    + "  WHERE invoice_date = date(billing_date) "
                    + "ORDER  BY 3,2,1,5 ";
}
