//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.09 at 02:46:25 PM IST 
//


package com.sapienter.jbilling.server.mediation.sapphire.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChargeIndicatorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ChargeIndicatorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="No Indication"/>
 *     &lt;enumeration value="No Charge"/>
 *     &lt;enumeration value="Charge"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ChargeIndicatorType")
@XmlEnum
public enum ChargeIndicatorType {


    /**
     * No indication of call charge.
     *           
     * 
     */
    @XmlEnumValue("No Indication")
    NO_INDICATION("No Indication"),

    /**
     * The called party indicated there is no charge for this
     *             call.
     *           
     * 
     */
    @XmlEnumValue("No Charge")
    NO_CHARGE("No Charge"),

    /**
     * The called party indicated there will be a charge for
     *             this call.
     *           
     * 
     */
    @XmlEnumValue("Charge")
    CHARGE("Charge");
    private final String value;

    ChargeIndicatorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChargeIndicatorType fromValue(String v) {
        for (ChargeIndicatorType c: ChargeIndicatorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
