//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.09 at 02:46:25 PM IST 
//


package com.sapienter.jbilling.server.mediation.sapphire.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Contains a list of User Defined String Attributes
 *         associated with a call.
 * 
 *         Introduced: Version 1.0, Compatibility Level 9.
 *       
 * 
 * <p>Java class for UDSAsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UDSAsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UDSA" type="{http://www.metaswitch.com/cfs/billing/V1.0}UDSAType" maxOccurs="10" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UDSAsType", propOrder = {
    "udsa"
})
public class UDSAsType {

    @XmlElement(name = "UDSA")
    protected List<UDSAType> udsa;

    /**
     * Gets the value of the udsa property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the udsa property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUDSA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UDSAType }
     * 
     * 
     */
    public List<UDSAType> getUDSA() {
        if (udsa == null) {
            udsa = new ArrayList<UDSAType>();
        }
        return this.udsa;
    }

}
