/*
 * JBILLING CONFIDENTIAL
 * _____________________
 *
 * [2003] - [2012] Enterprise jBilling Software Ltd.
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Enterprise jBilling Software.
 * The intellectual and technical concepts contained
 * herein are proprietary to Enterprise jBilling Software
 * and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden.
 */

package com.sapienter.jbilling.server.order;


import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

/**
 * OrderProcessWS
 *
 * @author Brian Cowdery
 * @since 25-10-2010
 */
@ApiModel(value = "Order process data", description = "OrderProcessWS model")
public class OrderProcessWS implements Serializable {

    private Integer id;
    private Integer billingProcessId;
    private Integer orderId;
    private Integer invoiceId;
    private Integer periodsIncluded;
    private Date periodStart;
    private Date periodEnd;
    private Integer isReview;
    private Integer origin;

    public OrderProcessWS() {
    }

    @ApiModelProperty(value = "Unique identifier of the order process")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ApiModelProperty(value = "Unique identifier of the billing process for which the order process is defined")
    public Integer getBillingProcessId() {
        return billingProcessId;
    }

    public void setBillingProcessId(Integer billingProcessId) {
        this.billingProcessId = billingProcessId;
    }

    @ApiModelProperty(value = "Unique identifier of the order to which this process applies")
    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @ApiModelProperty(value = "Unique identifier of the invoice generated by the order process")
    public Integer getInvoiceId() {
        return invoiceId;
    }

    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }

    @ApiModelProperty(value = "Number of included periods in the order process")
    public Integer getPeriodsIncluded() {
        return periodsIncluded;
    }

    public void setPeriodsIncluded(Integer periodsIncluded) {
        this.periodsIncluded = periodsIncluded;
    }

    @ApiModelProperty(value = "Start date for the period of the order process")
    public Date getPeriodStart() {
        return periodStart;
    }

    public void setPeriodStart(Date periodStart) {
        this.periodStart = periodStart;
    }

    @ApiModelProperty(value = "End date for the period of the order process")
    public Date getPeriodEnd() {
        return periodEnd;
    }

    public void setPeriodEnd(Date periodEnd) {
        this.periodEnd = periodEnd;
    }

    @ApiModelProperty(value = "Flag that is set if the process is a review")
    public Integer getReview() {
        return isReview;
    }

    public void setReview(Integer review) {
        isReview = review;
    }

    @ApiModelProperty(value = "Flag that describres what kind of procedure created the order process." +
            "1 - billing process; 2 - manually. ")
    public Integer getOrigin() {
        return origin;
    }

    public void setOrigin(Integer origin) {
        this.origin = origin;
    }

    @Override
    public String toString() {
        return "OrderProcessWS{"
               + "id=" + id
               + ", orderId=" + orderId
               + ", invoiceId=" + invoiceId
               + ", periodsIncluded=" + periodsIncluded
               + ", periodStart=" + periodStart
               + ", periodEnd=" + periodEnd
               + ", isReview=" + isReview
               + ", origin=" + origin
               + '}';
    }
}
