ALTER TABLE reset_password_code ADD CONSTRAINT reset_password_code_base_user_id_key UNIQUE (base_user_id);
ALTER TABLE rate_card ADD CONSTRAINT rate_card_table_name_key UNIQUE (table_name);
ALTER TABLE plan_item_price_timeline ADD CONSTRAINT plnitmprctimelnprc_mdl_key UNIQUE (price_model_id);
ALTER TABLE payment_method_template ADD CONSTRAINT payment_method_template_template_name_key UNIQUE (template_name);
ALTER TABLE meta_field_value ADD CONSTRAINT meta_field_value_id_key UNIQUE (id);
ALTER TABLE item_price_timeline ADD CONSTRAINT itmprctimelnprc_model_id_key UNIQUE (price_model_id);
ALTER TABLE item_entity_map ADD CONSTRAINT item_entity_map_uc_1 UNIQUE (entity_id, item_id);
ALTER TABLE customer_account_info_type_timeline ADD CONSTRAINT customer_account_info_type_timeline_uk UNIQUE (customer_id, meta_field_value_id, account_info_type_id);
--ALTER TABLE asset_entity_map ADD CONSTRAINT asset_entity_map_uc_1 UNIQUE (asset_id, entity_id);
ALTER TABLE ageing_entity_step ADD CONSTRAINT entity_step_days UNIQUE (entity_id, days);
ALTER TABLE validation_rule ADD CONSTRAINT validation_rule_pkey PRIMARY KEY (id);
ALTER TABLE user_status ADD CONSTRAINT user_status_pkey PRIMARY KEY (id);
ALTER TABLE user_role_map ADD CONSTRAINT user_role_map_compositekey PRIMARY KEY (user_id, role_id);
ALTER TABLE user_code_link ADD CONSTRAINT user_code_link_pkey PRIMARY KEY (id);
ALTER TABLE user_code ADD CONSTRAINT user_code_pkey PRIMARY KEY (id);
ALTER TABLE usage_pool_consumption_log ADD CONSTRAINT usage_pool_consumption_log_pkey PRIMARY KEY (id);
ALTER TABLE usage_pool_consumption_actions ADD CONSTRAINT usage_pool_consumption_actions_pkey PRIMARY KEY (id);
ALTER TABLE usage_pool_consumption_action ADD CONSTRAINT usage_pool_con_action_pkey PRIMARY KEY (id);
ALTER TABLE usage_pool ADD CONSTRAINT usage_pool_pkey PRIMARY KEY (id);
ALTER TABLE tab_configuration_tab ADD CONSTRAINT tab_configuration_tab_pkey PRIMARY KEY (id);
ALTER TABLE tab_configuration ADD CONSTRAINT tab_configuration_pkey PRIMARY KEY (id);
ALTER TABLE tab ADD CONSTRAINT tab_pkey PRIMARY KEY (id);
ALTER TABLE sure_tax_txn_log ADD CONSTRAINT sure_tax_txn_log_pkey PRIMARY KEY (id);
ALTER TABLE shortcut ADD CONSTRAINT shortcut_pkey PRIMARY KEY (id);
ALTER TABLE route_rate_card ADD CONSTRAINT route_rate_card_pkey PRIMARY KEY (id);
ALTER TABLE route ADD CONSTRAINT route_pkey PRIMARY KEY (id);
ALTER TABLE role ADD CONSTRAINT role_pkey PRIMARY KEY (id);
ALTER TABLE reset_password_code ADD CONSTRAINT pk_reset_password_code PRIMARY KEY (token);
ALTER TABLE reserved_amounts ADD CONSTRAINT reserved_amounts_pkey PRIMARY KEY (id);
ALTER TABLE report_type ADD CONSTRAINT report_type_pkey PRIMARY KEY (id);
ALTER TABLE report_parameter ADD CONSTRAINT report_parameter_pkey PRIMARY KEY (id);
ALTER TABLE report ADD CONSTRAINT report_pkey PRIMARY KEY (id);
ALTER TABLE recent_item ADD CONSTRAINT recent_item_pkey PRIMARY KEY (id);
ALTER TABLE rating_unit ADD CONSTRAINT pk_rating_unit PRIMARY KEY (id);
ALTER TABLE rate_card ADD CONSTRAINT rate_card_pkey PRIMARY KEY (id);
ALTER TABLE purchase_order ADD CONSTRAINT purchase_order_pkey PRIMARY KEY (id);
ALTER TABLE provisioning_request ADD CONSTRAINT provisioning_request_pkey PRIMARY KEY (id);
ALTER TABLE provisioning_command ADD CONSTRAINT provisioning_command_pkey PRIMARY KEY (id);
ALTER TABLE promotion_user_map ADD CONSTRAINT promotion_user_map_compositekey PRIMARY KEY (user_id, promotion_id);
ALTER TABLE promotion ADD CONSTRAINT promotion_pkey PRIMARY KEY (id);
ALTER TABLE process_run_user ADD CONSTRAINT process_run_user_pkey PRIMARY KEY (id);
ALTER TABLE process_run_total_pm ADD CONSTRAINT process_run_total_pm_pkey PRIMARY KEY (id);
ALTER TABLE process_run_total ADD CONSTRAINT process_run_total_pkey PRIMARY KEY (id);
ALTER TABLE process_run ADD CONSTRAINT process_run_pkey PRIMARY KEY (id);
ALTER TABLE price_model_attribute ADD CONSTRAINT price_model_attribute_pkey PRIMARY KEY (price_model_id, attribute_name);
ALTER TABLE price_model ADD CONSTRAINT price_model_pkey PRIMARY KEY (id);
ALTER TABLE preference_type ADD CONSTRAINT preference_type_pkey PRIMARY KEY (id);
ALTER TABLE preference ADD CONSTRAINT preference_pkey PRIMARY KEY (id);
ALTER TABLE pluggable_task_type_category ADD CONSTRAINT pluggable_task_type_cat_pkey PRIMARY KEY (id);
ALTER TABLE pluggable_task_type ADD CONSTRAINT pluggable_task_type_pkey PRIMARY KEY (id);
ALTER TABLE pluggable_task_parameter ADD CONSTRAINT pluggable_task_parameter_pkey PRIMARY KEY (id);
ALTER TABLE pluggable_task ADD CONSTRAINT pluggable_task_pkey PRIMARY KEY (id);
ALTER TABLE plan_item_price_timeline ADD CONSTRAINT plan_item_price_timeline_pkey PRIMARY KEY (plan_item_id, start_date);
ALTER TABLE plan_item_bundle ADD CONSTRAINT plan_item_bundle_pkey PRIMARY KEY (id);
ALTER TABLE plan_item ADD CONSTRAINT plan_item_pkey PRIMARY KEY (id);
ALTER TABLE plan ADD CONSTRAINT plan_pkey PRIMARY KEY (id);
ALTER TABLE permission_user ADD CONSTRAINT permission_user_pkey PRIMARY KEY (id);
ALTER TABLE permission_type ADD CONSTRAINT permission_type_pkey PRIMARY KEY (id);
ALTER TABLE permission ADD CONSTRAINT permission_pkey PRIMARY KEY (id);
ALTER TABLE period_unit ADD CONSTRAINT period_unit_pkey PRIMARY KEY (id);
ALTER TABLE payment_result ADD CONSTRAINT payment_result_pkey PRIMARY KEY (id);
ALTER TABLE payment_method_type ADD CONSTRAINT payment_method_type_pkey PRIMARY KEY (id);
ALTER TABLE payment_method_template ADD CONSTRAINT payment_method_template_pkey PRIMARY KEY (id);
ALTER TABLE payment_method ADD CONSTRAINT payment_method_pkey PRIMARY KEY (id);
ALTER TABLE payment_meta_field_map ADD CONSTRAINT payment_meta_field_map_compositekey PRIMARY KEY (payment_id, meta_field_value_id);
ALTER TABLE payment_invoice ADD CONSTRAINT payment_invoice_pkey PRIMARY KEY (id);
ALTER TABLE payment_instrument_info ADD CONSTRAINT payment_instrument_info_pkey PRIMARY KEY (id);
ALTER TABLE payment_information ADD CONSTRAINT payment_information_pkey PRIMARY KEY (id);
ALTER TABLE payment_info_cheque ADD CONSTRAINT payment_info_cheque_pkey PRIMARY KEY (id);
ALTER TABLE payment_authorization ADD CONSTRAINT payment_authorization_pkey PRIMARY KEY (id);
ALTER TABLE payment ADD CONSTRAINT payment_pkey PRIMARY KEY (id);
ALTER TABLE partner_payout ADD CONSTRAINT partner_payout_pkey PRIMARY KEY (id);
ALTER TABLE partner_meta_field_map ADD CONSTRAINT partner_meta_field_map_compositekey PRIMARY KEY (partner_id, meta_field_value_id);
ALTER TABLE partner ADD CONSTRAINT partner_pkey PRIMARY KEY (id);
ALTER TABLE paper_invoice_batch ADD CONSTRAINT paper_invoice_batch_pkey PRIMARY KEY (id);
ALTER TABLE order_status ADD CONSTRAINT order_status_pkey PRIMARY KEY (id);
ALTER TABLE order_process ADD CONSTRAINT order_process_pkey PRIMARY KEY (id);
ALTER TABLE order_period ADD CONSTRAINT order_period_pkey PRIMARY KEY (id);
ALTER TABLE order_meta_field_map ADD CONSTRAINT order_meta_field_map_compositekey PRIMARY KEY (order_id, meta_field_value_id);
ALTER TABLE order_line_usage_pool_map ADD CONSTRAINT order_line_usage_pool_map_pkey PRIMARY KEY (id);
ALTER TABLE order_line_type ADD CONSTRAINT order_line_type_pkey PRIMARY KEY (id);
ALTER TABLE order_line ADD CONSTRAINT order_line_pkey PRIMARY KEY (id);
ALTER TABLE order_change_type ADD CONSTRAINT order_change_type_pkey PRIMARY KEY (id);
ALTER TABLE order_change_plan_item ADD CONSTRAINT porder_change_plan_item_pkey PRIMARY KEY (id);
ALTER TABLE order_change ADD CONSTRAINT order_change_pkey PRIMARY KEY (id);
ALTER TABLE order_billing_type ADD CONSTRAINT order_billing_type_pkey PRIMARY KEY (id);
ALTER TABLE notification_message_type ADD CONSTRAINT notifictn_msg_type_pkey PRIMARY KEY (id);
ALTER TABLE notification_message_section ADD CONSTRAINT notifictn_msg_section_pkey PRIMARY KEY (id);
ALTER TABLE notification_message_line ADD CONSTRAINT notifictn_msg_line_pkey PRIMARY KEY (id);
ALTER TABLE notification_message_arch_line ADD CONSTRAINT notifictn_msg_arch_line_pkey PRIMARY KEY (id);
ALTER TABLE notification_message_arch ADD CONSTRAINT notifictn_msg_arch_pkey PRIMARY KEY (id);
ALTER TABLE notification_message ADD CONSTRAINT notifictn_msg_pkey PRIMARY KEY (id);
ALTER TABLE notification_medium_type ADD CONSTRAINT pk_notification_medium_type PRIMARY KEY (notification_id, medium_type);
ALTER TABLE notification_category ADD CONSTRAINT notification_category_pk PRIMARY KEY (id);
ALTER TABLE meta_field_name ADD CONSTRAINT meta_field_name_pkey PRIMARY KEY (id);
ALTER TABLE meta_field_group ADD CONSTRAINT metafield_group_pkey PRIMARY KEY (id);
ALTER TABLE mediation_process ADD CONSTRAINT mediation_process_pkey PRIMARY KEY (id);
ALTER TABLE mediation_order_map ADD CONSTRAINT mediation_order_map_compositekey PRIMARY KEY (mediation_process_id, order_id);
ALTER TABLE mediation_errors ADD CONSTRAINT mediation_errors_pkey PRIMARY KEY (accountcode);
ALTER TABLE mediation_cfg ADD CONSTRAINT mediation_cfg_pkey PRIMARY KEY (id);
ALTER TABLE matching_field ADD CONSTRAINT matching_field_pkey PRIMARY KEY (id);
ALTER TABLE language ADD CONSTRAINT language_pkey PRIMARY KEY (id);
ALTER TABLE jbilling_table ADD CONSTRAINT jbilling_table_pkey PRIMARY KEY (id);
ALTER TABLE jbilling_seqs ADD CONSTRAINT jbilling_seqs_pk PRIMARY KEY (name);
ALTER TABLE item_type_map ADD CONSTRAINT item_type_map_compositekey PRIMARY KEY (item_id, type_id);
ALTER TABLE item_type_exclude_map ADD CONSTRAINT item_type_exclude_map_pkey PRIMARY KEY (item_id, type_id);
ALTER TABLE item_type ADD CONSTRAINT item_type_pkey PRIMARY KEY (id);
ALTER TABLE item_price_timeline ADD CONSTRAINT item_price_timeline_pkey PRIMARY KEY (model_map_id, start_date);
ALTER TABLE item_meta_field_map ADD CONSTRAINT item_meta_field_map_compositekey PRIMARY KEY (item_id, meta_field_value_id);
ALTER TABLE item_dependency ADD CONSTRAINT item_dependency_pk PRIMARY KEY (id);
ALTER TABLE item ADD CONSTRAINT item_pkey PRIMARY KEY (id);
ALTER TABLE invoice_meta_field_map ADD CONSTRAINT invoice_meta_field_map_compositekey PRIMARY KEY (invoice_id, meta_field_value_id);
ALTER TABLE invoice_line_type ADD CONSTRAINT invoice_line_type_pkey PRIMARY KEY (id);
ALTER TABLE invoice_line ADD CONSTRAINT invoice_line_pkey PRIMARY KEY (id);
ALTER TABLE invoice_delivery_method ADD CONSTRAINT invoice_delivery_method_pkey PRIMARY KEY (id);
ALTER TABLE invoice ADD CONSTRAINT invoice_pkey PRIMARY KEY (id);
ALTER TABLE international_description ADD CONSTRAINT international_description_pkey PRIMARY KEY (table_id, foreign_id, psudo_column, language_id);
ALTER TABLE generic_status_type ADD CONSTRAINT generic_status_type_pkey PRIMARY KEY (id);
ALTER TABLE generic_status ADD CONSTRAINT generic_status_pkey PRIMARY KEY (id);
ALTER TABLE filter_set ADD CONSTRAINT filter_set_pkey PRIMARY KEY (id);
ALTER TABLE filter ADD CONSTRAINT filter_pkey PRIMARY KEY (id);
ALTER TABLE event_log_module ADD CONSTRAINT event_log_module_pkey PRIMARY KEY (id);
ALTER TABLE event_log_message ADD CONSTRAINT event_log_message_pkey PRIMARY KEY (id);
ALTER TABLE event_log ADD CONSTRAINT event_log_pkey PRIMARY KEY (id);
ALTER TABLE enumeration_values ADD CONSTRAINT enumeration_values_pkey PRIMARY KEY (id);
ALTER TABLE enumeration ADD CONSTRAINT enumeration_pkey PRIMARY KEY (id);
ALTER TABLE entity_report_map ADD CONSTRAINT entity_report_map_compositekey PRIMARY KEY (report_id, entity_id);
ALTER TABLE entity_payment_method_map ADD CONSTRAINT entity_payment_method_map_compositekey PRIMARY KEY (entity_id, payment_method_id);
ALTER TABLE entity_item_price_map ADD CONSTRAINT item_price_model_map_pkey PRIMARY KEY (id);
ALTER TABLE entity_delivery_method_map ADD CONSTRAINT entity_delivery_method_map_compositekey PRIMARY KEY (method_id, entity_id);
ALTER TABLE entity ADD CONSTRAINT entity_pkey PRIMARY KEY (id);
ALTER TABLE discount_line ADD CONSTRAINT discount_line_pkey PRIMARY KEY (id);
ALTER TABLE discount_attribute ADD CONSTRAINT discount_attribute_pkey PRIMARY KEY (discount_id, attribute_name);
ALTER TABLE discount ADD CONSTRAINT discount_pkey PRIMARY KEY (id);
--ALTER TABLE databasechangeloglock ADD CONSTRAINT pk_databasechangeloglock PRIMARY KEY (id);
--ALTER TABLE databasechangelog ADD CONSTRAINT pk_databasechangelog PRIMARY KEY (id, author, filename);
ALTER TABLE data_table_query_entry ADD CONSTRAINT pk_data_table_query_entry PRIMARY KEY (id);
ALTER TABLE data_table_query ADD CONSTRAINT pk_data_table_query PRIMARY KEY (id);
ALTER TABLE customer_usage_pool_map ADD CONSTRAINT customer_usage_pool_map_pkey PRIMARY KEY (id);
ALTER TABLE customer_price ADD CONSTRAINT customer_price_pkey PRIMARY KEY (plan_item_id, user_id);
ALTER TABLE customer_notes ADD CONSTRAINT pk_customer_notes PRIMARY KEY (id);
ALTER TABLE customer_meta_field_map ADD CONSTRAINT customer_meta_field_map_compositekey PRIMARY KEY (customer_id, meta_field_value_id);
ALTER TABLE customer_account_info_type_timeline ADD CONSTRAINT customer_account_info_type_timeline_pkey PRIMARY KEY (id);
ALTER TABLE customer ADD CONSTRAINT customer_pkey PRIMARY KEY (id);
ALTER TABLE currency_exchange ADD CONSTRAINT currency_exchange_pkey PRIMARY KEY (id);
ALTER TABLE currency_entity_map ADD CONSTRAINT currency_entity_map_compositekey PRIMARY KEY (currency_id, entity_id);
ALTER TABLE currency ADD CONSTRAINT currency_pkey PRIMARY KEY (id);
ALTER TABLE credit_card ADD CONSTRAINT credit_card_pkey PRIMARY KEY (id);
ALTER TABLE country ADD CONSTRAINT country_pkey PRIMARY KEY (id);
ALTER TABLE contact_map ADD CONSTRAINT contact_map_pkey PRIMARY KEY (id);
ALTER TABLE contact ADD CONSTRAINT contact_pkey PRIMARY KEY (id);
ALTER TABLE charge_sessions ADD CONSTRAINT charge_sessions_pkey PRIMARY KEY (id);
ALTER TABLE cdrentries ADD CONSTRAINT cdrentries_pkey PRIMARY KEY (id);
ALTER TABLE breadcrumb ADD CONSTRAINT breadcrumb_pkey PRIMARY KEY (id);
ALTER TABLE blacklist ADD CONSTRAINT blacklist_pkey PRIMARY KEY (id);
ALTER TABLE billing_process_failed_user ADD CONSTRAINT billing_process_failed_user_pkey PRIMARY KEY (id);
ALTER TABLE billing_process_configuration ADD CONSTRAINT billing_process_config_pkey PRIMARY KEY (id);
ALTER TABLE billing_process ADD CONSTRAINT billing_process_pkey PRIMARY KEY (id);
ALTER TABLE batch_step_execution_context ADD CONSTRAINT batch_step_execution_context_pkey PRIMARY KEY (step_execution_id);
ALTER TABLE batch_step_execution ADD CONSTRAINT batch_step_execution_pkey PRIMARY KEY (step_execution_id);
ALTER TABLE batch_process_info ADD CONSTRAINT billing_process_info_pkey PRIMARY KEY (id);
ALTER TABLE batch_job_instance ADD CONSTRAINT batch_job_instance_pkey PRIMARY KEY (job_instance_id);
ALTER TABLE batch_job_execution_context ADD CONSTRAINT batch_job_execution_context_pkey PRIMARY KEY (job_execution_id);
ALTER TABLE batch_job_execution ADD CONSTRAINT batch_job_execution_pkey PRIMARY KEY (job_execution_id);
ALTER TABLE base_user ADD CONSTRAINT base_user_pkey PRIMARY KEY (id);
ALTER TABLE asset_transition ADD CONSTRAINT asset_transition_pkey PRIMARY KEY (id);
ALTER TABLE asset_status ADD CONSTRAINT asset_status_pkey PRIMARY KEY (id);
ALTER TABLE asset ADD CONSTRAINT asset_pkey PRIMARY KEY (id);
ALTER TABLE ageing_entity_step ADD CONSTRAINT ageing_entity_step_pkey PRIMARY KEY (id);
ALTER TABLE ach ADD CONSTRAINT ach_pkey PRIMARY KEY (id);
ALTER TABLE account_type ADD CONSTRAINT account_type_pkey PRIMARY KEY (id);
ALTER TABLE validation_rule_attributes ADD CONSTRAINT validation_rule_fk_2 FOREIGN KEY (validation_rule_id) REFERENCES validation_rule(id);
ALTER TABLE user_role_map ADD CONSTRAINT user_role_map_fk_2 FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE user_role_map ADD CONSTRAINT user_role_map_fk_1 FOREIGN KEY (role_id) REFERENCES role(id);
ALTER TABLE usage_pool_item_type_map ADD CONSTRAINT usage_pool_item_type_map_fk_2 FOREIGN KEY (item_type_id) REFERENCES item_type(id);
ALTER TABLE usage_pool_item_type_map ADD CONSTRAINT usage_pool_item_type_map_fk_1 FOREIGN KEY (usage_pool_id) REFERENCES usage_pool(id);
ALTER TABLE usage_pool_item_map ADD CONSTRAINT usage_pool_item_map_fk_2 FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE usage_pool_item_map ADD CONSTRAINT usage_pool_item_map_fk_1 FOREIGN KEY (usage_pool_id) REFERENCES usage_pool(id);
ALTER TABLE usage_pool_consumption_log ADD CONSTRAINT usage_pool_consumption_log_fk FOREIGN KEY (customer_usage_pool_id) REFERENCES customer_usage_pool_map(id);
ALTER TABLE usage_pool_consumption_actions ADD CONSTRAINT usage_pool_consumption_actions_fk FOREIGN KEY (usage_pool_id) REFERENCES usage_pool(id);
ALTER TABLE usage_pool_attribute ADD CONSTRAINT usage_pool_attr_pool_id_fk FOREIGN KEY (usage_pool_id) REFERENCES usage_pool(id);
ALTER TABLE usage_pool ADD CONSTRAINT usage_pool_entity_id_fk FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE tab_configuration_tab ADD CONSTRAINT tab_configuration_tab_fk_2 FOREIGN KEY (tab_configuration_id) REFERENCES tab_configuration(id);
ALTER TABLE tab_configuration_tab ADD CONSTRAINT tab_configuration_tab_fk_1 FOREIGN KEY (tab_id) REFERENCES tab(id);
ALTER TABLE tab_configuration ADD CONSTRAINT tab_configuration_fk_1 FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE route_rate_card ADD CONSTRAINT route_rate_card_rating_unit_id FOREIGN KEY (rating_unit_id) REFERENCES rating_unit(id);
ALTER TABLE role ADD CONSTRAINT role_entity_id_fk FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE reserved_amounts ADD CONSTRAINT fk_reservations_session FOREIGN KEY (session_id) REFERENCES charge_sessions(id);
ALTER TABLE reseller_entityid_map ADD CONSTRAINT reseller_entityid_map_fk_2 FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE reseller_entityid_map ADD CONSTRAINT reseller_entityid_map_fk_1 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE rating_unit ADD CONSTRAINT rating_unit_entity_id_FK FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE rate_card_child_entity_map ADD CONSTRAINT rate_card_child_entity_map_fk2 FOREIGN KEY (rate_card_id) REFERENCES rate_card(id);
ALTER TABLE rate_card_child_entity_map ADD CONSTRAINT rate_card_child_entity_map_fk1 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE rate_card ADD CONSTRAINT rate_card_entity_id_fk FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE purchase_order ADD CONSTRAINT purchase_order_statusId_fk FOREIGN KEY (status_id) REFERENCES order_status(id);
ALTER TABLE purchase_order ADD CONSTRAINT purchase_order_parent__order_id_fk FOREIGN KEY (parent_order_id) REFERENCES purchase_order(id);
ALTER TABLE purchase_order ADD CONSTRAINT purchase_order_fk_5 FOREIGN KEY (created_by) REFERENCES base_user(id);
ALTER TABLE purchase_order ADD CONSTRAINT purchase_order_fk_4 FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE purchase_order ADD CONSTRAINT purchase_order_fk_3 FOREIGN KEY (period_id) REFERENCES order_period(id);
ALTER TABLE purchase_order ADD CONSTRAINT purchase_order_fk_2 FOREIGN KEY (billing_type_id) REFERENCES order_billing_type(id);
ALTER TABLE purchase_order ADD CONSTRAINT purchase_order_fk_1 FOREIGN KEY (currency_id) REFERENCES currency(id);
ALTER TABLE purchase_order ADD CONSTRAINT order_primary_order_fk_1 FOREIGN KEY (primary_order_id) REFERENCES purchase_order(id);
ALTER TABLE provisioning_request_result_map ADD CONSTRAINT provisioning_request_result_fk_1 FOREIGN KEY (provisioning_request_id) REFERENCES provisioning_request(id);
ALTER TABLE provisioning_command_parameter_map ADD CONSTRAINT provisioning_command_parameter_fk_1 FOREIGN KEY (provisioning_command_id) REFERENCES provisioning_command(id);
ALTER TABLE provisioning_command ADD CONSTRAINT entity_provisioning_command_fk_1 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE promotion_user_map ADD CONSTRAINT promotion_user_map_fk_2 FOREIGN KEY (promotion_id) REFERENCES promotion(id);
ALTER TABLE promotion_user_map ADD CONSTRAINT promotion_user_map_fk_1 FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE promotion ADD CONSTRAINT promotion_fk_1 FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE process_run_user ADD CONSTRAINT process_run_user_fk_2 FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE process_run_user ADD CONSTRAINT process_run_user_fk_1 FOREIGN KEY (process_run_id) REFERENCES process_run(id);
ALTER TABLE process_run_total_pm ADD CONSTRAINT process_run_total_pm_fk_1 FOREIGN KEY (payment_method_id) REFERENCES payment_method(id);
ALTER TABLE process_run_total ADD CONSTRAINT process_run_total_fk_2 FOREIGN KEY (process_run_id) REFERENCES process_run(id);
ALTER TABLE process_run_total ADD CONSTRAINT process_run_total_fk_1 FOREIGN KEY (currency_id) REFERENCES currency(id);
ALTER TABLE process_run ADD CONSTRAINT process_run_fk_2 FOREIGN KEY (status_id) REFERENCES generic_status(id);
ALTER TABLE process_run ADD CONSTRAINT process_run_fk_1 FOREIGN KEY (process_id) REFERENCES billing_process(id);
ALTER TABLE price_model_attribute ADD CONSTRAINT price_model_attr_model_id_fk FOREIGN KEY (price_model_id) REFERENCES price_model(id);
ALTER TABLE price_model ADD CONSTRAINT price_model_next_id_fk FOREIGN KEY (next_model_id) REFERENCES price_model(id);
ALTER TABLE price_model ADD CONSTRAINT price_model_currency_id_fk FOREIGN KEY (currency_id) REFERENCES currency(id);
ALTER TABLE price_model ADD CONSTRAINT price_model_company_id_fk FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE preference ADD CONSTRAINT preference_fk_2 FOREIGN KEY (table_id) REFERENCES jbilling_table(id);
ALTER TABLE preference ADD CONSTRAINT preference_fk_1 FOREIGN KEY (type_id) REFERENCES preference_type(id);
ALTER TABLE pluggable_task_type ADD CONSTRAINT pluggable_task_type_fk_1 FOREIGN KEY (category_id) REFERENCES pluggable_task_type_category(id);
ALTER TABLE pluggable_task_parameter ADD CONSTRAINT pluggable_task_parameter_fk_1 FOREIGN KEY (task_id) REFERENCES pluggable_task(id);
ALTER TABLE pluggable_task ADD CONSTRAINT pluggable_task_fk_2 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE pluggable_task ADD CONSTRAINT pluggable_task_fk_1 FOREIGN KEY (type_id) REFERENCES pluggable_task_type(id);
ALTER TABLE plan_usage_pool_map ADD CONSTRAINT plan_usage_pool_map_fk_2 FOREIGN KEY (usage_pool_id) REFERENCES usage_pool(id);
ALTER TABLE plan_usage_pool_map ADD CONSTRAINT plan_usage_pool_map_fk_1 FOREIGN KEY (plan_id) REFERENCES plan(id);
ALTER TABLE plan_meta_field_map ADD CONSTRAINT plan_meta_field_map_fk_2 FOREIGN KEY (meta_field_value_id) REFERENCES meta_field_value(id);
ALTER TABLE plan_meta_field_map ADD CONSTRAINT plan_meta_field_map_fk_1 FOREIGN KEY (plan_id) REFERENCES plan(id);
ALTER TABLE plan_item_price_timeline ADD CONSTRAINT plnitmtimelnprc_mode_fk FOREIGN KEY (price_model_id) REFERENCES price_model(id);
ALTER TABLE plan_item_price_timeline ADD CONSTRAINT plan_itm_timelin_plan_itm_fk FOREIGN KEY (plan_item_id) REFERENCES plan_item(id);
ALTER TABLE plan_item_bundle ADD CONSTRAINT plan_item_bundle_period_fk FOREIGN KEY (period_id) REFERENCES order_period(id);
ALTER TABLE plan_item ADD CONSTRAINT plan_item_plan_id_fk FOREIGN KEY (plan_id) REFERENCES plan(id);
ALTER TABLE plan_item ADD CONSTRAINT plan_item_item_id_fk FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE plan_item ADD CONSTRAINT plan_item_bundle_id_fk FOREIGN KEY (plan_item_bundle_id) REFERENCES plan_item_bundle(id);
ALTER TABLE plan ADD CONSTRAINT plan_period_id_fk FOREIGN KEY (period_id) REFERENCES order_period(id);
ALTER TABLE plan ADD CONSTRAINT plan_item_id_fk FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE permission_user ADD CONSTRAINT permission_user_fk_2 FOREIGN KEY (permission_id) REFERENCES permission(id);
ALTER TABLE permission_user ADD CONSTRAINT permission_user_fk_1 FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE permission_role_map ADD CONSTRAINT permission_role_map_fk_2 FOREIGN KEY (permission_id) REFERENCES permission(id);
ALTER TABLE permission_role_map ADD CONSTRAINT permission_role_map_fk_1 FOREIGN KEY (role_id) REFERENCES role(id);
ALTER TABLE permission ADD CONSTRAINT permission_fk_1 FOREIGN KEY (type_id) REFERENCES permission_type(id);
ALTER TABLE payment_provisioning_command_map ADD CONSTRAINT payment_provisioning_command_map_fk_2 FOREIGN KEY (payment_id) REFERENCES payment(id);
ALTER TABLE payment_provisioning_command_map ADD CONSTRAINT payment_provisioning_command_map_fk_1 FOREIGN KEY (provisioning_command_id) REFERENCES provisioning_command(id);
ALTER TABLE payment_method_type ADD CONSTRAINT payment_method_type_FK2 FOREIGN KEY (template_id) REFERENCES payment_method_template(id);
ALTER TABLE payment_method_type ADD CONSTRAINT payment_method_type_FK1 FOREIGN KEY (entity_id) REFERENCES entity(id);
--ALTER TABLE payment_method_template_meta_fields_map ADD CONSTRAINT payment_method_template_meta_fields_map_FK2 FOREIGN KEY (meta_field_id) REFERENCES meta_field_name(id);
ALTER TABLE payment_method_template_meta_fields_map ADD CONSTRAINT payment_method_template_meta_fields_map_FK1 FOREIGN KEY (method_template_id) REFERENCES payment_method_template(id);
--ALTER TABLE payment_method_meta_fields_map ADD CONSTRAINT payment_method_meta_fields_map_FK2 FOREIGN KEY (meta_field_id) REFERENCES meta_field_name(id);
--ALTER TABLE payment_method_meta_fields_map ADD CONSTRAINT payment_method_meta_fields_map_FK1 FOREIGN KEY (payment_method_id) REFERENCES payment_method_type(id);
ALTER TABLE payment_method_account_type_map ADD CONSTRAINT payment_method_account_type_map_FK2 FOREIGN KEY (account_type_id) REFERENCES account_type(id);
--ALTER TABLE payment_method_account_type_map ADD CONSTRAINT payment_method_account_type_map_FK1 FOREIGN KEY (payment_method_id) REFERENCES payment_method_type(id);
ALTER TABLE payment_meta_field_map ADD CONSTRAINT payment_meta_field_map_fk_2 FOREIGN KEY (meta_field_value_id) REFERENCES meta_field_value(id);
ALTER TABLE payment_meta_field_map ADD CONSTRAINT payment_meta_field_map_fk_1 FOREIGN KEY (payment_id) REFERENCES payment(id);
ALTER TABLE payment_invoice ADD CONSTRAINT payment_invoice_fk_2 FOREIGN KEY (payment_id) REFERENCES payment(id);
ALTER TABLE payment_invoice ADD CONSTRAINT payment_invoice_fk_1 FOREIGN KEY (invoice_id) REFERENCES invoice(id);
ALTER TABLE payment_instrument_info ADD CONSTRAINT payment_instrument_info_FK4 FOREIGN KEY (payment_id) REFERENCES payment(id);
ALTER TABLE payment_instrument_info ADD CONSTRAINT payment_instrument_info_FK3 FOREIGN KEY (instrument_id) REFERENCES payment_information(id);
ALTER TABLE payment_instrument_info ADD CONSTRAINT payment_instrument_info_FK2 FOREIGN KEY (method_id) REFERENCES payment_method(id);
ALTER TABLE payment_instrument_info ADD CONSTRAINT payment_instrument_info_FK1 FOREIGN KEY (result_id) REFERENCES payment_result(id);
ALTER TABLE payment_information_meta_fields_map ADD CONSTRAINT payment_information_meta_fields_map_FK2 FOREIGN KEY (meta_field_value_id) REFERENCES meta_field_value(id);
ALTER TABLE payment_information_meta_fields_map ADD CONSTRAINT payment_information_meta_fields_map_FK1 FOREIGN KEY (payment_information_id) REFERENCES payment_information(id);
--ALTER TABLE payment_information ADD CONSTRAINT payment_information_FK2 FOREIGN KEY (payment_method_id) REFERENCES payment_method_type(id);
ALTER TABLE payment_information ADD CONSTRAINT payment_information_FK1 FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE payment_info_cheque ADD CONSTRAINT payment_info_cheque_fk_1 FOREIGN KEY (payment_id) REFERENCES payment(id);
ALTER TABLE payment_authorization ADD CONSTRAINT payment_authorization_fk_1 FOREIGN KEY (payment_id) REFERENCES payment(id);
ALTER TABLE payment ADD CONSTRAINT payment_fk_6 FOREIGN KEY (method_id) REFERENCES payment_method(id);
ALTER TABLE payment ADD CONSTRAINT payment_fk_5 FOREIGN KEY (result_id) REFERENCES payment_result(id);
ALTER TABLE payment ADD CONSTRAINT payment_fk_4 FOREIGN KEY (credit_card_id) REFERENCES credit_card(id);
ALTER TABLE payment ADD CONSTRAINT payment_fk_3 FOREIGN KEY (payment_id) REFERENCES payment(id);
ALTER TABLE payment ADD CONSTRAINT payment_fk_2 FOREIGN KEY (currency_id) REFERENCES currency(id);
ALTER TABLE payment ADD CONSTRAINT payment_fk_1 FOREIGN KEY (ach_id) REFERENCES ach(id);
ALTER TABLE partner_payout ADD CONSTRAINT partner_payout_fk_1 FOREIGN KEY (partner_id) REFERENCES partner(id);
ALTER TABLE partner_meta_field_map ADD CONSTRAINT partner_meta_field_map_fk_2 FOREIGN KEY (meta_field_value_id) REFERENCES meta_field_value(id);
ALTER TABLE partner_meta_field_map ADD CONSTRAINT partner_meta_field_map_fk_1 FOREIGN KEY (partner_id) REFERENCES partner(id);
ALTER TABLE partner_commission ADD CONSTRAINT partner_commission_currency_id_FK FOREIGN KEY (currency_id) REFERENCES currency(id);
ALTER TABLE partner ADD CONSTRAINT partner_fk_4 FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE order_provisioning_command_map ADD CONSTRAINT order_provisioning_command_map_fk_2 FOREIGN KEY (order_id) REFERENCES purchase_order(id);
ALTER TABLE order_provisioning_command_map ADD CONSTRAINT order_provisioning_command_map_fk_1 FOREIGN KEY (provisioning_command_id) REFERENCES provisioning_command(id);
ALTER TABLE order_process ADD CONSTRAINT order_process_fk_1 FOREIGN KEY (order_id) REFERENCES purchase_order(id);
ALTER TABLE order_period ADD CONSTRAINT order_period_fk_2 FOREIGN KEY (unit_id) REFERENCES period_unit(id);
ALTER TABLE order_period ADD CONSTRAINT order_period_fk_1 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE order_meta_field_map ADD CONSTRAINT order_meta_field_map_fk_2 FOREIGN KEY (meta_field_value_id) REFERENCES meta_field_value(id);
ALTER TABLE order_meta_field_map ADD CONSTRAINT order_meta_field_map_fk_1 FOREIGN KEY (order_id) REFERENCES purchase_order(id);
ALTER TABLE order_line_usage_pool_map ADD CONSTRAINT order_line_usage_pool_map_fk_2 FOREIGN KEY (customer_usage_pool_id) REFERENCES customer_usage_pool_map(id);
ALTER TABLE order_line_usage_pool_map ADD CONSTRAINT order_line_usage_pool_map_fk_1 FOREIGN KEY (order_line_id) REFERENCES order_line(id);
ALTER TABLE order_line_provisioning_command_map ADD CONSTRAINT order_line_provisioning_command_map_fk_2 FOREIGN KEY (order_change_id) REFERENCES order_change(id);
ALTER TABLE order_line_provisioning_command_map ADD CONSTRAINT order_line_provisioning_command_map_fk_1 FOREIGN KEY (provisioning_command_id) REFERENCES provisioning_command(id);
ALTER TABLE order_line_meta_fields_map ADD CONSTRAINT ol_meta_fields_map_fk_2 FOREIGN KEY (meta_field_id) REFERENCES meta_field_name(id);
ALTER TABLE order_line_meta_fields_map ADD CONSTRAINT ol_meta_fields_map_fk_1 FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE order_line_meta_field_map ADD CONSTRAINT ol_meta_field_map_fk_2 FOREIGN KEY (meta_field_value_id) REFERENCES meta_field_value(id);
ALTER TABLE order_line_meta_field_map ADD CONSTRAINT ol_meta_field_map_fk_1 FOREIGN KEY (order_line_id) REFERENCES order_line(id);
ALTER TABLE order_line ADD CONSTRAINT order_line_parent_line_id_fk FOREIGN KEY (parent_line_id) REFERENCES order_line(id);
ALTER TABLE order_line ADD CONSTRAINT order_line_fk_3 FOREIGN KEY (type_id) REFERENCES order_line_type(id);
ALTER TABLE order_line ADD CONSTRAINT order_line_fk_2 FOREIGN KEY (order_id) REFERENCES purchase_order(id);
ALTER TABLE order_line ADD CONSTRAINT order_line_fk_1 FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE order_change_type_meta_field_map ADD CONSTRAINT order_change_type_meta_field_map_meta_field_id_fk FOREIGN KEY (meta_field_id) REFERENCES meta_field_name(id);
ALTER TABLE order_change_type_meta_field_map ADD CONSTRAINT order_change_type_meta_field_map_change_type_id_fk FOREIGN KEY (order_change_type_id) REFERENCES order_change_type(id);
ALTER TABLE order_change_type_item_type_map ADD CONSTRAINT order_change_type_item_type_map_item_type_id_fk FOREIGN KEY (item_type_id) REFERENCES item_type(id);
ALTER TABLE order_change_type_item_type_map ADD CONSTRAINT order_change_type_item_type_map_change_type_id_fk FOREIGN KEY (order_change_type_id) REFERENCES order_change_type(id);
ALTER TABLE order_change_type ADD CONSTRAINT order_change_type_entity_id_fk FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE order_change_plan_item_meta_field_map ADD CONSTRAINT order_change_plan_item_meta_field_map_fk2 FOREIGN KEY (meta_field_value_id) REFERENCES meta_field_value(id);
ALTER TABLE order_change_plan_item_meta_field_map ADD CONSTRAINT order_change_plan_item_meta_field_map_fk1 FOREIGN KEY (order_change_plan_item_id) REFERENCES order_change_plan_item(id);
ALTER TABLE order_change_plan_item_asset_map ADD CONSTRAINT order_change_plan_item_asset_map_fk2 FOREIGN KEY (asset_id) REFERENCES asset(id);
ALTER TABLE order_change_plan_item_asset_map ADD CONSTRAINT order_change_plan_item_asset_map_fk1 FOREIGN KEY (order_change_plan_item_id) REFERENCES order_change_plan_item(id);
ALTER TABLE order_change_plan_item ADD CONSTRAINT order_change_plan_item_fk2 FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE order_change_plan_item ADD CONSTRAINT order_change_plan_item_fk1 FOREIGN KEY (order_change_id) REFERENCES order_change(id);
ALTER TABLE order_change_meta_field_map ADD CONSTRAINT order_change_meta_field_map_fk_2 FOREIGN KEY (meta_field_value_id) REFERENCES meta_field_value(id);
ALTER TABLE order_change_meta_field_map ADD CONSTRAINT order_change_meta_field_map_fk_1 FOREIGN KEY (order_change_id) REFERENCES order_change(id);
ALTER TABLE order_change_asset_map ADD CONSTRAINT order_change_asset_map_change_id_fk FOREIGN KEY (order_change_id) REFERENCES order_change(id);
ALTER TABLE order_change_asset_map ADD CONSTRAINT order_change_asset_map_asset_id_fk FOREIGN KEY (asset_id) REFERENCES asset(id);
ALTER TABLE order_change ADD CONSTRAINT order_change_user_status_id_fk FOREIGN KEY (user_assigned_status_id) REFERENCES generic_status(id);
ALTER TABLE order_change ADD CONSTRAINT order_change_user_id_fk FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE order_change ADD CONSTRAINT order_change_status_id_fk FOREIGN KEY (status_id) REFERENCES generic_status(id);
ALTER TABLE order_change ADD CONSTRAINT order_change_parent_order_line_id_fk FOREIGN KEY (parent_order_line_id) REFERENCES order_line(id);
ALTER TABLE order_change ADD CONSTRAINT order_change_parent_order_change_fk FOREIGN KEY (parent_order_change_id) REFERENCES order_change(id);
ALTER TABLE order_change ADD CONSTRAINT order_change_order_status_id_fk FOREIGN KEY (order_status_id) REFERENCES order_status(id);
ALTER TABLE order_change ADD CONSTRAINT order_change_order_line_id_fk FOREIGN KEY (order_line_id) REFERENCES order_line(id);
ALTER TABLE order_change ADD CONSTRAINT order_change_order_id_fk FOREIGN KEY (order_id) REFERENCES purchase_order(id);
ALTER TABLE order_change ADD CONSTRAINT order_change_order_change_type_id_fk FOREIGN KEY (order_change_type_id) REFERENCES order_change_type(id);
ALTER TABLE order_change ADD CONSTRAINT order_change_item_id_fk FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE notification_message_type ADD CONSTRAINT category_id_fk_1 FOREIGN KEY (category_id) REFERENCES notification_category(id);
ALTER TABLE notification_message_section ADD CONSTRAINT notification_msg_section_fk_1 FOREIGN KEY (message_id) REFERENCES notification_message(id);
ALTER TABLE notification_message_line ADD CONSTRAINT notification_message_line_fk_1 FOREIGN KEY (message_section_id) REFERENCES notification_message_section(id);
ALTER TABLE notification_message_arch_line ADD CONSTRAINT notif_mess_arch_line_fk_1 FOREIGN KEY (message_archive_id) REFERENCES notification_message_arch(id);
ALTER TABLE notification_message ADD CONSTRAINT notification_message_fk_3 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE notification_message ADD CONSTRAINT notification_message_fk_2 FOREIGN KEY (type_id) REFERENCES notification_message_type(id);
ALTER TABLE notification_message ADD CONSTRAINT notification_message_fk_1 FOREIGN KEY (language_id) REFERENCES language(id);
ALTER TABLE nested_plan ADD CONSTRAINT nested_plan_plan_id_fk FOREIGN KEY (plan_id) REFERENCES plan(id);
ALTER TABLE nested_plan ADD CONSTRAINT nested_plan_parent_plan_id_fk FOREIGN KEY (parent_plan_id) REFERENCES plan(id);
--ALTER TABLE meta_field_value ADD CONSTRAINT meta_field_value_fk_1 FOREIGN KEY (meta_field_name_id) REFERENCES meta_field_name(id);
ALTER TABLE meta_field_name ADD CONSTRAINT validation_rule_fk_1 FOREIGN KEY (validation_rule_id) REFERENCES validation_rule(id);
ALTER TABLE meta_field_name ADD CONSTRAINT meta_field_name_fk_1 FOREIGN KEY (default_value_id) REFERENCES meta_field_value(id);
ALTER TABLE meta_field_name ADD CONSTRAINT meta_field_entity_id_fk FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE meta_field_group ADD CONSTRAINT account_type_main_subscription_period_FK2 FOREIGN KEY (account_type_id) REFERENCES account_type(id);
ALTER TABLE mediation_process ADD CONSTRAINT mediation_process_fk_1 FOREIGN KEY (configuration_id) REFERENCES mediation_cfg(id);
ALTER TABLE mediation_order_map ADD CONSTRAINT mediation_order_map_fk_2 FOREIGN KEY (order_id) REFERENCES purchase_order(id);
ALTER TABLE mediation_order_map ADD CONSTRAINT mediation_order_map_fk_1 FOREIGN KEY (mediation_process_id) REFERENCES mediation_process(id);
ALTER TABLE mediation_cfg ADD CONSTRAINT mediation_cfg_fk_1 FOREIGN KEY (pluggable_task_id) REFERENCES pluggable_task(id);
ALTER TABLE mediation_cfg ADD CONSTRAINT fk_mediation_cfg_root_route FOREIGN KEY (root_route) REFERENCES route(id);
ALTER TABLE matching_field ADD CONSTRAINT matching_field_route_rate_card_id_FK FOREIGN KEY (route_rate_card_id) REFERENCES route_rate_card(id);
ALTER TABLE matching_field ADD CONSTRAINT matching_field_route_id_FK FOREIGN KEY (route_id) REFERENCES route(id);
ALTER TABLE item_type_meta_field_def_map ADD CONSTRAINT item_type_meta_field_def_map_fk_2 FOREIGN KEY (meta_field_id) REFERENCES meta_field_name(id);
ALTER TABLE item_type_meta_field_def_map ADD CONSTRAINT item_type_meta_field_def_map_fk_1 FOREIGN KEY (item_type_id) REFERENCES item_type(id);
ALTER TABLE item_type_map ADD CONSTRAINT item_type_map_fk_2 FOREIGN KEY (type_id) REFERENCES item_type(id);
ALTER TABLE item_type_map ADD CONSTRAINT item_type_map_fk_1 FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE item_type_exclude_map ADD CONSTRAINT item_type_exclude_type_id_fk FOREIGN KEY (type_id) REFERENCES item_type(id);
ALTER TABLE item_type_exclude_map ADD CONSTRAINT item_type_exclude_item_id_fk FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE item_type_entity_map ADD CONSTRAINT item_type_entity_map_fk2 FOREIGN KEY (item_type_id) REFERENCES item_type(id);
ALTER TABLE item_type_entity_map ADD CONSTRAINT item_type_entity_map_fk1 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE item_type ADD CONSTRAINT parent_id_fk FOREIGN KEY (parent_id) REFERENCES item_type(id);
ALTER TABLE item_type ADD CONSTRAINT item_type_fk_1 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE item_price_timeline ADD CONSTRAINT item_pm_map_price_model_id_fk FOREIGN KEY (price_model_id) REFERENCES price_model(id);
ALTER TABLE item_price_timeline ADD CONSTRAINT item_pm_map_model_map_id_fk FOREIGN KEY (model_map_id) REFERENCES entity_item_price_map(id);
ALTER TABLE item_meta_field_map ADD CONSTRAINT item_meta_field_map_fk_2 FOREIGN KEY (meta_field_value_id) REFERENCES meta_field_value(id);
ALTER TABLE item_meta_field_map ADD CONSTRAINT item_meta_field_map_fk_1 FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE item_entity_map ADD CONSTRAINT item_entity_map_fk2 FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE item_entity_map ADD CONSTRAINT item_entity_map_fk1 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE item_dependency ADD CONSTRAINT item_dependency_fk3 FOREIGN KEY (dependent_item_type_id) REFERENCES item_type(id);
ALTER TABLE item_dependency ADD CONSTRAINT item_dependency_fk2 FOREIGN KEY (dependent_item_id) REFERENCES item(id);
ALTER TABLE item_dependency ADD CONSTRAINT item_dependency_fk1 FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE item ADD CONSTRAINT item_fk_1 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE invoice_meta_field_map ADD CONSTRAINT invoice_meta_field_map_fk_2 FOREIGN KEY (meta_field_value_id) REFERENCES meta_field_value(id);
ALTER TABLE invoice_meta_field_map ADD CONSTRAINT invoice_meta_field_map_fk_1 FOREIGN KEY (invoice_id) REFERENCES invoice(id);
ALTER TABLE invoice_line ADD CONSTRAINT invoice_line_fk_4 FOREIGN KEY (order_id) REFERENCES purchase_order(id);
ALTER TABLE invoice_line ADD CONSTRAINT invoice_line_fk_3 FOREIGN KEY (type_id) REFERENCES invoice_line_type(id);
ALTER TABLE invoice_line ADD CONSTRAINT invoice_line_fk_2 FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE invoice_line ADD CONSTRAINT invoice_line_fk_1 FOREIGN KEY (invoice_id) REFERENCES invoice(id);
ALTER TABLE invoice ADD CONSTRAINT invoice_fk_4 FOREIGN KEY (delegated_invoice_id) REFERENCES invoice(id);
ALTER TABLE invoice ADD CONSTRAINT invoice_fk_3 FOREIGN KEY (currency_id) REFERENCES currency(id);
ALTER TABLE invoice ADD CONSTRAINT invoice_fk_2 FOREIGN KEY (paper_invoice_batch_id) REFERENCES paper_invoice_batch(id);
ALTER TABLE invoice ADD CONSTRAINT invoice_fk_1 FOREIGN KEY (billing_process_id) REFERENCES billing_process(id);
ALTER TABLE international_description ADD CONSTRAINT international_description_fk_1 FOREIGN KEY (language_id) REFERENCES language(id);
ALTER TABLE generic_status ADD CONSTRAINT generic_status_fk_1 FOREIGN KEY (dtype) REFERENCES generic_status_type(id);
ALTER TABLE generic_status ADD CONSTRAINT generic_status_entity_id_fk FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE event_log ADD CONSTRAINT event_log_fk_6 FOREIGN KEY (affected_user_id) REFERENCES base_user(id);
ALTER TABLE event_log ADD CONSTRAINT event_log_fk_5 FOREIGN KEY (message_id) REFERENCES event_log_message(id);
ALTER TABLE event_log ADD CONSTRAINT event_log_fk_4 FOREIGN KEY (table_id) REFERENCES jbilling_table(id);
ALTER TABLE event_log ADD CONSTRAINT event_log_fk_3 FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE event_log ADD CONSTRAINT event_log_fk_2 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE event_log ADD CONSTRAINT event_log_fk_1 FOREIGN KEY (module_id) REFERENCES event_log_module(id);
ALTER TABLE enumeration_values ADD CONSTRAINT enumeration_values_fk_1 FOREIGN KEY (enumeration_id) REFERENCES enumeration(id);
ALTER TABLE entity_report_map ADD CONSTRAINT report_map_report_id_fk FOREIGN KEY (report_id) REFERENCES report(id);
ALTER TABLE entity_report_map ADD CONSTRAINT report_map_entity_id_fk FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE entity_payment_method_map ADD CONSTRAINT entity_payment_method_map_fk_2 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE entity_payment_method_map ADD CONSTRAINT entity_payment_method_map_fk_1 FOREIGN KEY (payment_method_id) REFERENCES payment_method(id);
ALTER TABLE entity_item_price_map ADD CONSTRAINT item_price_model_map_fk2 FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE entity_item_price_map ADD CONSTRAINT item_price_model_map_fk1 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE entity_delivery_method_map ADD CONSTRAINT entity_delivry_methd_map_fk2 FOREIGN KEY (method_id) REFERENCES invoice_delivery_method(id);
ALTER TABLE entity_delivery_method_map ADD CONSTRAINT entity_delivry_methd_map_fk1 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE entity ADD CONSTRAINT entity_fk_3 FOREIGN KEY (parent_id) REFERENCES entity(id);
ALTER TABLE entity ADD CONSTRAINT entity_fk_2 FOREIGN KEY (language_id) REFERENCES language(id);
ALTER TABLE entity ADD CONSTRAINT entity_fk_1 FOREIGN KEY (currency_id) REFERENCES currency(id);
ALTER TABLE discount_line ADD CONSTRAINT discount_line_plan_item_id_fk FOREIGN KEY (plan_item_id) REFERENCES plan_item(id);
ALTER TABLE discount_line ADD CONSTRAINT discount_line_order_line_id_fk FOREIGN KEY (discount_order_line_id) REFERENCES order_line(id);
ALTER TABLE discount_line ADD CONSTRAINT discount_line_order_id_fk FOREIGN KEY (order_id) REFERENCES purchase_order(id);
ALTER TABLE discount_line ADD CONSTRAINT discount_line_item_id_fk FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE discount_line ADD CONSTRAINT discount_line_discount_id_fk FOREIGN KEY (discount_id) REFERENCES discount(id);
ALTER TABLE discount_attribute ADD CONSTRAINT discount_attr_id_fk FOREIGN KEY (discount_id) REFERENCES discount(id);
ALTER TABLE discount ADD CONSTRAINT discount_entity_id_fk FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE data_table_query_entry ADD CONSTRAINT data_table_query_entry_next_FK FOREIGN KEY (next_entry_id) REFERENCES data_table_query_entry(id);
ALTER TABLE data_table_query ADD CONSTRAINT data_table_query_next_FK FOREIGN KEY (root_entry_id) REFERENCES data_table_query_entry(id);
ALTER TABLE customer_usage_pool_map ADD CONSTRAINT customer_usage_pool_map_fk_2 FOREIGN KEY (usage_pool_id) REFERENCES usage_pool(id);
ALTER TABLE customer_usage_pool_map ADD CONSTRAINT customer_usage_pool_map_fk_1 FOREIGN KEY (customer_id) REFERENCES customer(id);
ALTER TABLE customer_price ADD CONSTRAINT customer_price_user_id_fk FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE customer_price ADD CONSTRAINT customer_price_plan_item_id_fk FOREIGN KEY (plan_item_id) REFERENCES plan_item(id);
ALTER TABLE customer_notes ADD CONSTRAINT customer_notes_user_id_FK FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE customer_notes ADD CONSTRAINT customer_notes_entity_id_FK FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE customer_notes ADD CONSTRAINT customer_notes_customer_id_FK FOREIGN KEY (customer_id) REFERENCES customer(id);
ALTER TABLE customer_meta_field_map ADD CONSTRAINT customer_meta_field_map_fk_2 FOREIGN KEY (meta_field_value_id) REFERENCES meta_field_value(id);
ALTER TABLE customer_meta_field_map ADD CONSTRAINT customer_meta_field_map_fk_1 FOREIGN KEY (customer_id) REFERENCES customer(id);
ALTER TABLE customer_account_info_type_timeline ADD CONSTRAINT customer_account_info_type_timeline_meta_field_value_id_fk FOREIGN KEY (meta_field_value_id) REFERENCES meta_field_value(id);
ALTER TABLE customer_account_info_type_timeline ADD CONSTRAINT customer_account_info_type_timeline_customer_id_fk FOREIGN KEY (customer_id) REFERENCES customer(id);
ALTER TABLE customer_account_info_type_timeline ADD CONSTRAINT customer_account_info_type_timeline_account_info_type_id_fk FOREIGN KEY (account_info_type_id) REFERENCES meta_field_group(id);
ALTER TABLE customer ADD CONSTRAINT customer_main_subscription_period_FK FOREIGN KEY (main_subscript_order_period_id) REFERENCES order_period(id);
ALTER TABLE customer ADD CONSTRAINT customer_fk_3 FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE customer ADD CONSTRAINT customer_fk_2 FOREIGN KEY (partner_id) REFERENCES partner(id);
ALTER TABLE customer ADD CONSTRAINT customer_fk_1 FOREIGN KEY (invoice_delivery_method_id) REFERENCES invoice_delivery_method(id);
ALTER TABLE customer ADD CONSTRAINT customer_account_type_fk FOREIGN KEY (account_type_id) REFERENCES account_type(id);
ALTER TABLE currency_exchange ADD CONSTRAINT currency_exchange_fk_1 FOREIGN KEY (currency_id) REFERENCES currency(id);
ALTER TABLE currency_entity_map ADD CONSTRAINT currency_entity_map_fk_2 FOREIGN KEY (currency_id) REFERENCES currency(id);
ALTER TABLE currency_entity_map ADD CONSTRAINT currency_entity_map_fk_1 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE contact_map ADD CONSTRAINT contact_map_fk_3 FOREIGN KEY (contact_id) REFERENCES contact(id);
ALTER TABLE contact_map ADD CONSTRAINT contact_map_fk_1 FOREIGN KEY (table_id) REFERENCES jbilling_table(id);
ALTER TABLE charge_sessions ADD CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE blacklist ADD CONSTRAINT blacklist_fk_4 FOREIGN KEY (meta_field_value_id) REFERENCES meta_field_value(id);
ALTER TABLE blacklist ADD CONSTRAINT blacklist_fk_2 FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE blacklist ADD CONSTRAINT blacklist_fk_1 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE billing_process_configuration ADD CONSTRAINT billing_proc_configtn_fk_2 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE billing_process ADD CONSTRAINT billing_process_fk_3 FOREIGN KEY (paper_invoice_batch_id) REFERENCES paper_invoice_batch(id);
ALTER TABLE billing_process ADD CONSTRAINT billing_process_fk_2 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE billing_process ADD CONSTRAINT billing_process_fk_1 FOREIGN KEY (period_unit_id) REFERENCES period_unit(id);
ALTER TABLE base_user ADD CONSTRAINT base_user_fk_6 FOREIGN KEY (status_id) REFERENCES user_status(id);
ALTER TABLE base_user ADD CONSTRAINT base_user_fk_5 FOREIGN KEY (currency_id) REFERENCES currency(id);
ALTER TABLE base_user ADD CONSTRAINT base_user_fk_4 FOREIGN KEY (language_id) REFERENCES language(id);
ALTER TABLE base_user ADD CONSTRAINT base_user_fk_3 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE asset_transition ADD CONSTRAINT asset_transition_fk_5 FOREIGN KEY (previous_status_id) REFERENCES asset_status(id);
ALTER TABLE asset_transition ADD CONSTRAINT asset_transition_fk_4 FOREIGN KEY (new_status_id) REFERENCES asset_status(id);
ALTER TABLE asset_transition ADD CONSTRAINT asset_transition_fk_3 FOREIGN KEY (asset_id) REFERENCES asset(id);
ALTER TABLE asset_transition ADD CONSTRAINT asset_transition_fk_2 FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE asset_transition ADD CONSTRAINT asset_transition_fk_1 FOREIGN KEY (assigned_to_id) REFERENCES base_user(id);
ALTER TABLE asset_status ADD CONSTRAINT asset_status_fk_1 FOREIGN KEY (item_type_id) REFERENCES item_type(id);
ALTER TABLE asset_provisioning_command_map ADD CONSTRAINT asset_provisioning_command_map_fk_2 FOREIGN KEY (asset_id) REFERENCES asset(id);
ALTER TABLE asset_provisioning_command_map ADD CONSTRAINT asset_provisioning_command_map_fk_1 FOREIGN KEY (provisioning_command_id) REFERENCES provisioning_command(id);
ALTER TABLE asset_meta_field_map ADD CONSTRAINT asset_meta_field_map_fk_2 FOREIGN KEY (meta_field_value_id) REFERENCES meta_field_value(id);
ALTER TABLE asset_meta_field_map ADD CONSTRAINT asset_meta_field_map_fk_1 FOREIGN KEY (asset_id) REFERENCES asset(id);
--ALTER TABLE asset_entity_map ADD CONSTRAINT asset_entity_map_fk2 FOREIGN KEY (asset_id) REFERENCES asset(id);
--ALTER TABLE asset_entity_map ADD CONSTRAINT asset_entity_map_fk1 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE asset ADD CONSTRAINT asset_fk_4 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE asset ADD CONSTRAINT asset_fk_3 FOREIGN KEY (status_id) REFERENCES asset_status(id);
ALTER TABLE asset ADD CONSTRAINT asset_fk_2 FOREIGN KEY (order_line_id) REFERENCES order_line(id);
ALTER TABLE asset ADD CONSTRAINT asset_fk_1 FOREIGN KEY (item_id) REFERENCES item(id);
ALTER TABLE ageing_entity_step ADD CONSTRAINT ageing_entity_step_fk_2 FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE ach ADD CONSTRAINT ach_fk_1 FOREIGN KEY (user_id) REFERENCES base_user(id);
ALTER TABLE account_type ADD CONSTRAINT invoice_delivery_method_id_FK FOREIGN KEY (invoice_delivery_method_id) REFERENCES invoice_delivery_method(id);
ALTER TABLE account_type ADD CONSTRAINT account_type_main_subscription_period_FK FOREIGN KEY (main_subscript_order_period_id) REFERENCES order_period(id);
ALTER TABLE account_type ADD CONSTRAINT account_type_language_id_FK FOREIGN KEY (language_id) REFERENCES language(id);
ALTER TABLE account_type ADD CONSTRAINT account_type_entity_id_FK FOREIGN KEY (entity_id) REFERENCES entity(id);
ALTER TABLE account_type ADD CONSTRAINT account_type_currency_id_FK FOREIGN KEY (currency_id) REFERENCES currency(id);


