update databasechangelog set md5sum = null where id = 'min-balance-to-ignore-ageing';
update databasechangelog set md5sum = null where id = 'eliminate-main-order_alter-columns';
update databasechangelog set md5sum = null where id = 'eliminate-main-order_update-data-psql';
update databasechangelog set md5sum = null where id = 'fix-min_params_SimpleTaxCompositionTask';
update databasechangelog set md5sum = null where id = 'clear-empty-meta_fields';
update databasechangelog set md5sum = null where id = 'notification-message';
update databasechangelog set md5sum = null where id = 'add-subscription-event-processor';
update databasechangelog set md5sum = null where id = 'attach-overdue-invoices-to-notifications';
update databasechangelog set md5sum = null where id = 'mediation-console-jdbc-error-handler';
update databasechangelog set md5sum = null where id = '20120608-#2725-notification-category';
update databasechangelog set md5sum = null where id = 'custom-notification-feature';
update databasechangelog set md5sum = null where id = '20120606-2718-overdue-invoice-penalty-order-task';
update databasechangelog set md5sum = null where id = 'remove-rules-generator-task';
update databasechangelog set md5sum = null where id = 'add-event-based-custom-notification-task';
update databasechangelog set md5sum = null where id = 'add-new-simple-mediation-processor';
update databasechangelog set md5sum = null where id = '3990 - Made order_id persistent to invoiceLineDTO';
update databasechangelog set md5sum = null where id = '2006 - Force Unique Emails Preference';
update databasechangelog set md5sum = null where id = '4474 - Entity to be deletable.';
update databasechangelog set md5sum = null where id = 'change-category-for-penalty-task';
update databasechangelog set md5sum = null where id = 'add-new-suretax-engine-base';
update databasechangelog set md5sum = null where id = '20120809=#3198';
update databasechangelog set md5sum = null where id = '20121120 #3304 Jbilling Core Changes for Discounts';
update databasechangelog set md5sum = null where id = '20121213 #3452 Last Updated date time added on Discount';
update databasechangelog set md5sum = null where id = '20121031 #3530 Merchant Account Relationships';
update databasechangelog set md5sum = null where id = '4933 - Invoice Date and Invoice Due Date are Incorrect';
update databasechangelog set md5sum = null where id = 'fix-column-name-length';
update databasechangelog set md5sum = null where id = 'Requirement-5461';
update databasechangelog set md5sum = null where id = '1337623084753-66';
update databasechangelog set md5sum = null where id = '#6076-add-notification-for-refunds';
update databasechangelog set md5sum = null where id = '#6250-Tables-without-primary-keys';
update databasechangelog set md5sum = null where id = '#6183-credit-card-transaction-report-renamed-cc';
update databasechangelog set md5sum = null where id = '#6250-Tables-without-primary-keys - correction - 2';
update databasechangelog set md5sum = null where id = '#6250-Tables-without-primary-keys - correction - 3';
update databasechangelog set md5sum = null where id = '#7339 - Added to fix the null value in category Type dropdown';
/*jbilling-upgrade-3.3*/
update databasechangelog set md5sum = null where id = '#3173 - Create a New Payment Method ''Credit''';
update databasechangelog set md5sum = null where id = '#4781 - Dynamic tab configuration';
update databasechangelog set md5sum = null where id = '#4781 - Dynamic tab configuration - Discounts menu item';
update databasechangelog set md5sum = null where id = '#1905 - Reset password';
update databasechangelog set md5sum = null where id = '#3374-Ageing improvements';
update databasechangelog set md5sum = null where id = '20130305 - #3307';
update databasechangelog set md5sum = null where id = '20121207-#4042-add-parent-item-type-column';
update databasechangelog set md5sum = null where id = '20140310 - plan history report under plan reporttype';
update databasechangelog set md5sum = null where id = '#7623, Configure password rules';
/*jbilling-upgrade-3.4*/
update databasechangelog set md5sum = null where id = '#4938 - Asset Management - Permissions';
update databasechangelog set md5sum = null where id = '#4938 - Asset Management - Entites';
update databasechangelog set md5sum = null where id = '#4938 - Asset Management - Pluggable Tasks';
update databasechangelog set md5sum = null where id = '20130719 #5729: - Asset Groups - Entites';
update databasechangelog set md5sum = null where id = 'spring-batch-tables';
update databasechangelog set md5sum = null where id = 'spring-batch-key-gen-postgres';
update databasechangelog set md5sum = null where id = 'spring-batch-key-gen-mysql';
update databasechangelog set md5sum = null where id = 'Customer Account Type';
update databasechangelog set md5sum = null where id = 'add-account-type-in-jbilling_table';
update databasechangelog set md5sum = null where id = '5015-remove-auto-payment';
update databasechangelog set md5sum = null where id = '20130514-#4987-account-type-management';
update databasechangelog set md5sum = null where id = '20130516-#4988-account-type-pricing';
update databasechangelog set md5sum = null where id = '20130516-#4988-account-type-pricing-item-std-avail';
update databasechangelog set md5sum = null where id = '20130429-#4920';
update databasechangelog set md5sum = null where id = '20130429-#4920-bool-fix';
update databasechangelog set md5sum = null where id = '20130506-#4921';
update databasechangelog set md5sum = null where id = '20130513-#4922';
update databasechangelog set md5sum = null where id = '#5388-Java based Metafield validation';
update databasechangelog set md5sum = null where id = '#5137-remove-contact-type-constraints-on-contact-map';
update databasechangelog set md5sum = null where id = '20130531-#5237-product-dependencies';
update databasechangelog set md5sum = null where id = '#5293_product_inherited_order_meta_fields';
update databasechangelog set md5sum = null where id = '1337623084753-114';
update databasechangelog set md5sum = null where id = '#5338 Route-based Rating';
update databasechangelog set md5sum = null where id = '#5338 Route-RateCard Rating';
update databasechangelog set md5sum = null where id = '#5557 Matching Field';
update databasechangelog set md5sum = null where id = '#5373 - Development: Order Hierarchies';
update databasechangelog set md5sum = null where id = '#5712 - MF1J - Java based Metafield validation';
update databasechangelog set md5sum = null where id = '#5294_order_cancellation_fields';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 01';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 02';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 03';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 04';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 05';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 06';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 07';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 08';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 09';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 10';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 11';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 12';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 13';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 14';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - 15';
update databasechangelog set md5sum = null where id = 'requirement 5546 - 20130716';
update databasechangelog set md5sum = null where id = '#5408 - item-price-timeline';
update databasechangelog set md5sum = null where id = '#5408 - item-price-timeline - 2';
update databasechangelog set md5sum = null where id = '20130705-#5456';
update databasechangelog set md5sum = null where id = '#5487-script-meta-field';
update databasechangelog set md5sum = null where id = '#6168 - item_type_nullable_entity';
update databasechangelog set md5sum = null where id = '#6168 - unique constraint on item_entity_map';
update databasechangelog set md5sum = null where id = '#5711 - ait-timeline';
update databasechangelog set md5sum = null where id = '20130912-#5815 Minimum Quantities for Dependencies';
update databasechangelog set md5sum = null where id = '20130912-#5815 Migration';
update databasechangelog set md5sum = null where id = '20130830-#5611';
update databasechangelog set md5sum = null where id = 'springbatch - #5336 - 1';
update databasechangelog set md5sum = null where id = 'springbatch - #5336 - 3';
update databasechangelog set md5sum = null where id = '#5447 - Development: Order Changes as Entities';
update databasechangelog set md5sum = null where id = '#6719 - User Codes - Entities';
update databasechangelog set md5sum = null where id = '#6719 - User Codes - Permissions';
update databasechangelog set md5sum = null where id = '#6904 - Discounts - Permissions';
update databasechangelog set md5sum = null where id = '#6652 - Free Usage Pools';
update databasechangelog set md5sum = null where id = '#6593-order-line-tiers';
update databasechangelog set md5sum = null where id = '#6652-olt-free-usage-pools-association';
update databasechangelog set md5sum = null where id = '#6652-free-usage-pools-schedule-task';
update databasechangelog set md5sum = null where id = '#6652-olt-add-column';
update databasechangelog set md5sum = null where id = '#6652-Customer-Usage-Pool-Update';
update databasechangelog set md5sum = null where id = '#6652-order_line_usage_pool_map';
update databasechangelog set md5sum = null where id = '#6652-order-add-column';
update databasechangelog set md5sum = null where id = '2014-01-23#6904-Discounts Permissions-tables seqs';
update databasechangelog set md5sum = null where id = '#6652-customer-usage-pool-add-plan';
update databasechangelog set md5sum = null where id = '#6652-plan-unsubscribe-task';
update databasechangelog set md5sum = null where id = 'account-payment-information - #6315';
update databasechangelog set md5sum = null where id = '#7308-usage-pool-cunsumption-actions';
update databasechangelog set md5sum = null where id = '#7308-usage-pool-cunsumption-log';
update databasechangelog set md5sum = null where id = '#7308-usage-pool-fee-charging-task';
update databasechangelog set md5sum = null where id = 'requirement # 5292 - remove-asset-entity-not-null-constraint';
update databasechangelog set md5sum = null where id = '#5449 - Integrate Product Meta Fields into Order Changes';
update databasechangelog set md5sum = null where id = '#7308-usage-pool-consumption-notification';
update databasechangelog set md5sum = null where id = '#7308-usage-pool-consumption-notification-test';
update databasechangelog set md5sum = null where id = '#7633-fup-consumption-percentage-fix';
update databasechangelog set md5sum = null where id = '#7659-Free-Usage-Pool-Consumption-enhancements';
update databasechangelog set md5sum = null where id = '#7633-fup-consumption-percentage-fix-for-legacy-data';
update databasechangelog set md5sum = null where id = '#7308-fup-consumption-notification-fix1';
update databasechangelog set md5sum = null where id = '#7308-fup-consumption-notification-fix2';
update databasechangelog set md5sum = null where id = '#7308-fup-consumption-notification-fix3';
update databasechangelog set md5sum = null where id = '#7308-fup-consumption-notification-fix4';
update databasechangelog set md5sum = null where id = '#7308-fup-consumption-notification-fix5';
update databasechangelog set md5sum = null where id = '#7308-fup-consumption-notification-fix6';
update databasechangelog set md5sum = null where id = '#8048-usercodes-unique-per-company';
update databasechangelog set md5sum = null where id = '#0000 - Create new table provisioning_command';
update databasechangelog set md5sum = null where id = '#6571 - Provisioning monitoring GUI - Add provisioning menu';
update databasechangelog set md5sum = null where id = '7043 - Agents and Commissions';
update databasechangelog set md5sum = null where id = 'Source Readers: pluggable tasks';
update databasechangelog set md5sum = null where id = 'Source Readers: file exchange plugin';
update databasechangelog set md5sum = null where id = '#7514 - Plans Enhancement';
update databasechangelog set md5sum = null where id = '#5820_nested_plans';
update databasechangelog set md5sum = null where id = '#7806 plan order changes';
update databasechangelog set md5sum = null where id = '#6266-file-exchange-trigger';
update databasechangelog set md5sum = null where id = '#8099 - Update Show Discounts Menu permission type';
update databasechangelog set md5sum = null where id = '#7621 - MyAccount Permissions';
update databasechangelog set md5sum = null where id = '#7223 - Preference for enabling JQGrid on the site';
update databasechangelog set md5sum = null where id = '#8418 - adding currency to commissions';
update databasechangelog set md5sum = null where id = '#8009-Validation message for lnvalid ''expiry date'' field';
update databasechangelog set md5sum = null where id = '#6652 - Delete reference of order line tier';
update databasechangelog set md5sum = null where id = 'agent_default_preference';
update databasechangelog set md5sum = null where id = 'removed-order-line-tier';
/*jbilling-upgrade-4.0*/
update databasechangelog set md5sum = null where id = 'add-mediation-configuration-job-launcher';
update databasechangelog set md5sum = null where id = 'mediation-statistics-for-mediation-process';
update databasechangelog set md5sum = null where id = 'hbase-mediation-error-handler';
update databasechangelog set md5sum = null where id = 'add diameter entities';
update databasechangelog set md5sum = null where id = 'add diameter constraints';
update databasechangelog set md5sum = null where id = '#4184 - Implement ''Start Session'' API call';
update databasechangelog set md5sum = null where id = 'add data column to reserved_amounts table';
update databasechangelog set md5sum = null where id = 'add quantity column to reserved amounts table';
update databasechangelog set md5sum = null where id = 'add quantity multiplier';
update databasechangelog set md5sum = null where id = 'Add ''Subscriber URI'' metafield';
update databasechangelog set md5sum = null where id = '#4430 - Call details in order line item';
update databasechangelog set md5sum = null where id = 'Requirements #4501 - Per-customer automatic top-up parameters';
update databasechangelog set md5sum = null where id = 'add carried_units column to charge_sessions table';
update databasechangelog set md5sum = null where id = '20130510-#4989-customer-notes';
update databasechangelog set md5sum = null where id = '20130520-#4962-customer-notes';
update databasechangelog set md5sum = null where id = '20130703-#4434-mediation-record-changes';
update databasechangelog set md5sum = null where id = '20130820-add-rating-unit';
update databasechangelog set md5sum = null where id = '20130820-default-rating-unit-rate-card';
update databasechangelog set md5sum = null where id = 'hierarchical_routing';
update databasechangelog set md5sum = null where id = '20131024 hierarchical_routing - default_route';
update databasechangelog set md5sum = null where id = '#7543:multiple_root_for_mediation';
update databasechangelog set md5sum = null where id = '#7332-global-mediation-process';
update databasechangelog set md5sum = null where id = '20140220 #7520 - Order Changes Type';
update databasechangelog set md5sum = null where id = '20140227 #7520 Order Changes Type plugin for orderStatus change';
update databasechangelog set md5sum = null where id = '#7870:fix-product-id-in-route-tables';
update databasechangelog set md5sum = null where id = '#7899 - Subscription Products';
update databasechangelog set md5sum = null where id = '20140131-7219-save-nested-search-entities';
update databasechangelog set md5sum = null where id = '20140131-7219-save-nested-search-permissions';
update databasechangelog set md5sum = null where id = '#7045-data_tables-set_it_as_route_table_or_not';
update databasechangelog set md5sum = null where id = '#5188-Adding input directory field in mediation_cfg table';
update databasechangelog set md5sum = null where id = '20141008-#Bug Fix - Error in mediation, updating Records';
update databasechangelog set md5sum = null where id = 'AnswerConnect - Add entries in mediation_cfg table';
update databasechangelog set md5sum = null where id = 'AnswerConnect - Add entries in preference table';
update databasechangelog set md5sum = null where id = 'add-phone-number';
update databasechangelog set md5sum = null where id = '20140714 phone number';
update databasechangelog set md5sum = null where id = 'Inbound-View-mediation-errors';
update databasechangelog set md5sum = null where id = 'ActiveResponse-View-mediation-error';
update databasechangelog set md5sum = null where id = 'Chat-View-mediation-error';
update databasechangelog set md5sum = null where id = 'Inbound-mediation-configuration';
update databasechangelog set md5sum = null where id = 'Active-Response-mediation-configuration';
update databasechangelog set md5sum = null where id = 'Chat-mediation-configuration';
update databasechangelog set md5sum = null where id = 'Edit-Inbound-View-mediation-errors';
update databasechangelog set md5sum = null where id = 'Edit-ActiveResponse-View-mediation-error';
update databasechangelog set md5sum = null where id = 'Edit-Chat-View-mediation-error';
update databasechangelog set md5sum = null where id = '#2 Inbound-View-mediation-errors';
update databasechangelog set md5sum = null where id = '#2 ActiveResponse-View-mediation-error';
update databasechangelog set md5sum = null where id = '#2 Chat-View-mediation-error';
update databasechangelog set md5sum = null where id = 'AC Mediation Process Task';
update databasechangelog set md5sum = null where id = '#10375-update-jb-seqs-meta-field';
update databasechangelog set md5sum = null where id = 'Delete-Mediation-configuration';
update databasechangelog set md5sum = null where id = 'Delete-Mediation-Error-plugin-parameter';
update databasechangelog set md5sum = null where id = 'Delete-Mediation-Error-plugin';
update databasechangelog set md5sum = null where id = 'Adding-Global-Check';
update databasechangelog set md5sum = null where id = 'Updating international description';













