package com.sapienter.jbilling.server.provisioning;


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.sapienter.jbilling.server.security.WSSecured;
import com.sapienter.jbilling.server.timezone.ConvertToTimezone;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import static org.springframework.util.ObjectUtils.nullSafeEquals;
import static org.springframework.util.ObjectUtils.nullSafeHashCode;

@ApiModel(value = "Provisioning Command Data", description = "ProvisioningCommandWS model")
public class ProvisioningCommandWS implements WSSecured, Serializable {

    private static final long serialVersionUID = 20131125L;

    private int id;

    private Integer entityId;
    private String name;
    private Integer executionOrder;
    @ConvertToTimezone
    private Date createDate;
    @ConvertToTimezone
    private Date lastUpdateDate;

    private ProvisioningCommandType commandType;
    private ProvisioningCommandStatus commandStatus;

    private Map<String, String> parameterMap = new HashMap<String, String>();
    private ProvisioningRequestWS[] provisioningRequests;
    private Integer owningEntityId;

    private int versionNum;

    @ApiModelProperty(value = "The id is automatically assigned to the command information as it is generated by the system. It is jBilling’s method of identifying individual provisioning events")
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ApiModelProperty(value = "Id of the company for which this provisioning command is defined")
    public Integer getEntityId() {
        return entityId;
    }

    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    @ApiModelProperty(value = "This field matches the name on the provisioning list")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @ApiModelProperty(value = "Represents the order in which provisioning requests are sent to the correct external provisioning tasks")
    public Integer getExecutionOrder() {
        return executionOrder;
    }

    public void setExecutionOrder(Integer executionOrder) {
        this.executionOrder = executionOrder;
    }

    @ApiModelProperty(value = "This field matches the date on the provisioning list")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @ApiModelProperty(value = "This field defines the time the command was last processed")
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @ApiModelProperty(value = "This field matches the type on the provisioning list")
    public ProvisioningCommandType getCommandType() {
        return commandType;
    }

    public void setCommandType(ProvisioningCommandType commandType) {
        this.commandType = commandType;
    }

    @ApiModelProperty(value = "This field matches the status on the provisioning list")
    public ProvisioningCommandStatus getCommandStatus() {
        return commandStatus;
    }

    public void setCommandStatus(ProvisioningCommandStatus commandStatus) {
        this.commandStatus = commandStatus;
    }

    @ApiModelProperty(value = "Name and value map of parameters for the provisioning command")
    public Map<String, String> getParameterMap() {
        return parameterMap;
    }

    public void setParameterMap(Map<String, String> parameterMap) {
        this.parameterMap = parameterMap;
    }

    @ApiModelProperty(value = "Linked provisioning requests")
    public ProvisioningRequestWS[] getProvisioningRequests() {
        return provisioningRequests;
    }

    public void setProvisioningRequests(ProvisioningRequestWS[] provisioningRequests) {
        this.provisioningRequests = provisioningRequests;
    }

    @ApiModelProperty(value = "This field represents version number")
    public int getVersionNum() {
        return versionNum;
    }

    public void setVersionNum(int versionNum) {
        this.versionNum = versionNum;
    }

    @Override
    @JsonIgnore
    public Integer getOwningEntityId() {
        return owningEntityId;
    }

    public void setOwningEntityId(Integer owningEntityId) {
        this.owningEntityId = owningEntityId;
    }

    @Override
    @JsonIgnore
    public Integer getOwningUserId() {
        return null;  //To change body of implemented methods use File | Settings | File Templates.
    }

    @Override
    public String toString() {
        return "ProvisioningCommandWS{"
                + "id=" + id
                + ", entity_id=" + entityId
                + ", execution_order=" + executionOrder
                + ", create_date=" + createDate
                + ", last_update_date=" + lastUpdateDate
                + ", command_status=" + commandStatus
                + ", optlock=" + versionNum
                + '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProvisioningCommandWS)) return false;

        ProvisioningCommandWS that = (ProvisioningCommandWS) o;
        return id == that.id &&
                versionNum == that.versionNum &&
                nullSafeEquals(entityId, that.entityId) &&
                nullSafeEquals(name, that.name) &&
                nullSafeEquals(executionOrder, that.executionOrder) &&
                nullSafeEquals(createDate, that.createDate) &&
                nullSafeEquals(lastUpdateDate, that.lastUpdateDate) &&
                commandType == that.commandType &&
                commandStatus == that.commandStatus &&
                nullSafeEquals(parameterMap, that.parameterMap) &&
                nullSafeEquals(provisioningRequests, that.provisioningRequests) &&
                nullSafeEquals(owningEntityId, that.owningEntityId);
    }

    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + nullSafeHashCode(entityId);
        result = 31 * result + nullSafeHashCode(name);
        result = 31 * result + nullSafeHashCode(executionOrder);
        result = 31 * result + nullSafeHashCode(createDate);
        result = 31 * result + nullSafeHashCode(lastUpdateDate);
        result = 31 * result + nullSafeHashCode(commandType);
        result = 31 * result + nullSafeHashCode(commandStatus);
        result = 31 * result + nullSafeHashCode(parameterMap);
        result = 31 * result + nullSafeHashCode(provisioningRequests);
        result = 31 * result + nullSafeHashCode(owningEntityId);
        result = 31 * result + versionNum;
        return result;
    }
}
